Dolibarr: vCard Class Reference
vCard Class Reference
Class to buld vCard files.
Public Member Functions
setPhoneNumber ($number, $type="")
mise en forme du numero de telephone
setPhoto ($type, $photo)
mise en forme de la photo warning NON TESTE !
setFormattedName ($name)
mise en forme du nom formate
setName ($family="", $first="", $additional="", $prefix="", $suffix="")
mise en forme du nom complet
setBirthday ($date)
mise en forme de l'anniversaire
setAddress ($postoffice="", $extended="", $street="", $city="", $region="", $zip="", $country="", $type="HOME;POSTAL")
mise en forme de l'adresse
setLabel ($postoffice="", $extended="", $street="", $city="", $region="", $zip="", $country="", $type="HOME;POSTAL")
mise en forme du label
setEmail ($address, $type="TYPE=INTERNET;PREF")
Add a e-mail address to this vCard.
setNote ($note)
mise en forme de la note
setTitle ($title)
mise en forme de la fonction
setOrg ($org)
mise en forme de la societe
setProdId ($prodid)
mise en forme du logiciel generateur
setUID ($uid)
mise en forme du logiciel generateur
setURL ($url, $type="")
mise en forme de l'url
getVCard ()
permet d'obtenir une vcard
getFileName ()
permet d'obtenir le nom de fichier
Public Attributes
$properties
$filename
$encoding = "ISO-8859-1;ENCODING=QUOTED-PRINTABLE"
Detailed Description
Class to buld vCard files.
Definition at line 88 of file vcard.class.php.
Member Function Documentation
getFileName()
getFileName ()
permet d'obtenir le nom de fichier
Returns
string Filename
Definition at line 365 of file vcard.class.php.
getVCard()
getVCard ()
permet d'obtenir une vcard
Returns
string
Definition at line 346 of file vcard.class.php.
setAddress()
setAddress ($postoffice = "", $extended = "", $street = "", $city = "", $region = "", $zip = "", $country = "", $type = "HOME;POSTAL")
mise en forme de l'adresse
Parameters
string $postoffice Postoffice
string $extended Extended
string $street Street
string $city City
string $region Region
string $zip Zip
string $country Country
string $type Type
Returns
void
Definition at line 193 of file vcard.class.php.
setBirthday()
setBirthday ($date)
mise en forme de l'anniversaire
Parameters
integer $date Date
Returns
void
Definition at line 174 of file vcard.class.php.
setEmail()
setEmail ($address, $type = "TYPE=INTERNET;PREF")
Add a e-mail address to this vCard.
Parameters
string $address E-mail address
string $type (optional) The type of the e-mail (typical "PREF;INTERNET" or "INTERNET")
Returns
void
Definition at line 256 of file vcard.class.php.
setFormattedName()
setFormattedName ($name)
mise en forme du nom formate
Parameters
string $name Name
Returns
void
Definition at line 144 of file vcard.class.php.
setLabel()
setLabel ($postoffice = "", $extended = "", $street = "", $city = "", $region = "", $zip = "", $country = "", $type = "HOME;POSTAL")
mise en forme du label
Parameters
string $postoffice Postoffice
string $extended Extended
string $street Street
string $city City
string $region Region
string $zip Zip
string $country Country
string $type Type
Returns
void
Definition at line 221 of file vcard.class.php.
setName()
setName ($family = "", $first = "", $additional = "", $prefix = "", $suffix = "")
mise en forme du nom complet
Parameters
string $family Family name
string $first First name
string $additional Additional (e.g. second name, nick name)
string $prefix Prefix (e.g. "Mr.", "Ms.", "Prof.")
string $suffix Suffix (e.g. "sen." for senior, "jun." for junior)
Returns
void
Definition at line 159 of file vcard.class.php.
setNote()
setNote ($note)
mise en forme de la note
Parameters
string $note Note
Returns
void
Definition at line 271 of file vcard.class.php.
setOrg()
setOrg ($org)
mise en forme de la societe
Parameters
string $org Org
Returns
void
Definition at line 294 of file vcard.class.php.
References encode().
setPhoneNumber()
setPhoneNumber ($number, $type = "")
mise en forme du numero de telephone
Parameters
int $number numero de telephone
string $type Type
Returns
void
Definition at line 113 of file vcard.class.php.
setPhoto()
setPhoto ($type, $photo)
mise en forme de la photo warning NON TESTE !
Parameters
string $type Type
string $photo Photo
Returns
void
Definition at line 132 of file vcard.class.php.
setProdId()
setProdId ($prodid)
mise en forme du logiciel generateur
Parameters
string $prodid Prodid
Returns
void
Definition at line 306 of file vcard.class.php.
References encode().
setTitle()
setTitle ($title)
mise en forme de la fonction
Parameters
string $title Title
Returns
void
Definition at line 282 of file vcard.class.php.
References $title, and encode().
setUID()
setUID ($uid)
mise en forme du logiciel generateur
Parameters
string $uid Uid
Returns
void
Definition at line 318 of file vcard.class.php.
References encode().
setURL()
setURL ($url, $type = "")
mise en forme de l'url
Parameters
string $url URL
string $type Type
Returns
void
Definition at line 331 of file vcard.class.php.
The documentation for this class was generated from the following file:
htdocs/core/class/vcard.class.php