Dolibarr: htdocs/admin/system/modules.php File Reference
modules.php File Reference
File to list all Dolibarr modules.
Functions
compareIdAsc (stdClass $a, stdClass $b)
Compare two modules by their ID for a ascending order.
compareIdDesc (stdClass $a, stdClass $b)
Compare two modules by their ID for a descending order.
comparePermissionIdsAsc (stdClass $a, stdClass $b)
Compare two modules by their ID for a ascending order.
comparePermissionIdsDesc (stdClass $a, stdClass $b)
Compare two modules by their permissions for a descending order.
Variables
$optioncss = GETPOST('optioncss', 'alpha')
$contextpage = GETPOST('contextpage', 'aZ') ?GETPOST('contextpage', 'aZ') : 'moduleoverview'
$search_name = GETPOST("search_name", 'alpha')
$search_id = GETPOST("search_id", 'alpha')
$search_version = GETPOST("search_version", 'alpha')
$search_permission = GETPOST("search_permission", 'alpha')
$sortfield = GETPOST("sortfield", 'alpha')
$sortorder = GETPOST("sortorder", 'alpha')
$form = new Form($db)
$object = new stdClass()
$arrayfields
$param = ''
$parameters = array()
$reshook = $hookmanager->executeHooks('doActions', $parameters, $object, $action)
if($reshook< 0) if(empty($reshook)) $moduleList = array()
$modules = array()
$modules_files = array()
$modules_fullpath = array()
$modulesdir = dolGetModulesDirs()
$rights_ids = array()
$arrayofpermissions = array()
print $_SERVER ["PHP_SELF"]
print
$varpage = empty($contextpage) ? $_SERVER["PHP_SELF"] : $contextpage
$selectedfields = $form->multiSelectArrayWithCheckbox('selectedfields', $arrayfields, $varpage)
$searchpicto = $form->showFilterButtons()
print $hookmanager resPrint
if($sortfield=="name" && $sortorder=="asc") elseif($sortfield=="name" && $sortorder=="desc") elseif($sortfield=="version" && $sortorder=="asc") elseif($sortfield=="version" && $sortorder=="desc") elseif($sortfield=="id" && $sortorder=="asc") elseif($sortfield=="id" && $sortorder=="desc") elseif($sortfield=="permission" && $sortorder=="asc") elseif($sortfield=="permission" && $sortorder=="desc") else
$old = ''
Detailed Description
File to list all Dolibarr modules.
Definition in file modules.php.
Function Documentation
compareIdAsc()
compareIdAsc (stdClass $a, stdClass $b)
Compare two modules by their ID for a ascending order.
Parameters
stdClass $a First module
stdClass $b Second module
Returns
int Compare result (-1, 0, 1)
Definition at line 392 of file modules.php.
Referenced by comparePermissionIdsAsc().
compareIdDesc()
compareIdDesc (stdClass $a, stdClass $b)
Compare two modules by their ID for a descending order.
Parameters
stdClass $a First module
stdClass $b Second module
Returns
int Compare result (-1, 0, 1)
Definition at line 408 of file modules.php.
Referenced by comparePermissionIdsDesc().
comparePermissionIdsAsc()
comparePermissionIdsAsc (stdClass $a, stdClass $b)
Compare two modules by their ID for a ascending order.
Parameters
stdClass $a First module
stdClass $b Second module
Returns
int Compare result (-1, 0, 1)
Definition at line 424 of file modules.php.
References compareIdAsc().
comparePermissionIdsDesc()
comparePermissionIdsDesc (stdClass $a, stdClass $b)
Compare two modules by their permissions for a descending order.
Parameters
stdClass $a First module
stdClass $b Second module
Returns
int Compare result (-1, 0, 1)
Definition at line 451 of file modules.php.
References compareIdDesc().
Variable Documentation
$arrayfields
$arrayfields
Initial value:
= array(
    'name'=>array('label'=>$langs->trans("Modules"), 'checked'=>1, 'position'=>10),
    'version'=>array('label'=>$langs->trans("Version"), 'checked'=>1, 'position'=>20),
    'id'=>array('label'=>$langs->trans("IdModule"), 'checked'=>1, 'position'=>30),
    'module_position'=>array('label'=>$langs->trans("Position"), 'checked'=>1, 'position'=>35),
    'permission'=>array('label'=>$langs->trans("IdPermissions"), 'checked'=>1, 'position'=>40)
)
Definition at line 59 of file modules.php.
else
if ($sortfield=="name" &&$sortorder=="asc") elseif ($sortfield=="name" &&$sortorder=="desc") elseif ($sortfield=="version" &&$sortorder=="asc") elseif ($sortfield=="version" &&$sortorder=="desc") elseif ($sortfield=="id" &&$sortorder=="asc") elseif ($sortfield=="id" &&$sortorder=="desc") elseif ($sortfield=="permission" &&$sortorder=="asc") elseif ($sortfield=="permission" &&$sortorder=="desc") else
Initial value:
{
    $moduleList = dol_sort_array($moduleList, 'module_position')
Definition at line 314 of file modules.php.