FROM alpine:edge

LABEL maintainer="Jean Traullé <jtraulle@opencomp.fr>"

WORKDIR /home

RUN apk --update --no-cache add  \
        # Install dependencies used to build Doxygen from sources
        git cmake build-base python flex bison \
        # Used to generate diagrams
        # We do not forget to include the font (otherwise generated graphs will have squares instead of letters)
        graphviz ttf-freefont \
        # Used to build the PDF using the Makefile generated by Doxygen
        make \
        # Used to convert graphs and images inserted into the PDF
        ghostscript \
        # Main TeX distribution
        texmf-dist \
        texmf-dist-latexextra \
        texmf-dist-langgreek \
        texlive \
        texlive-luatex && \
    cd /root && \
    # Clonning latest version of Doxygen
    git clone https://github.com/doxygen/doxygen.git && \
    git config --global user.email "jtraulle@opencomp.fr" && \
    git config --global user.name "Jean Traullé" && \
    cd doxygen && \
    git checkout tags/Release_1_8_16 -b Release_1_8_16 && \
    # Applying patch for issue #7243
    git cherry-pick 4fe4ce026d75972018516d81507ae20db9cdc589 && \
    # Compiling Doxygen
    mkdir build && \
    cd build && \
    cmake -G "Unix Makefiles" .. && \
    make && \
    make install && \
    cd /home && \
    # Clean up
    apk del git cmake build-base python flex bison && \
    rm -rf /root/doxygen

