var group__mymodule =
[
    [ "about.php", "de/d11/modulebuilder_2template_2admin_2about_8php.html", null ],
    [ "myobject_extrafields.php", "de/ddc/myobject__extrafields_8php.html", null ],
    [ "setup.php", "d9/d24/modulebuilder_2template_2admin_2setup_8php.html", null ],
    [ "actions_mymodule.class.php", "d8/d93/actions__mymodule_8class_8php.html", null ],
    [ "api_mymodule.class.php", "d0/d28/api__mymodule_8class_8php.html", null ],
    [ "myobject.class.php", "d3/d01/myobject_8class_8php.html", null ],
    [ "mymodulewidget1.php", "d9/d64/mymodulewidget1_8php.html", null ],
    [ "interface_99_modMyModule_MyModuleTriggers.class.php", "de/d6a/interface__99__mod_my_module___my_module_triggers_8class_8php.html", null ],
    [ "mymodule.css.php", "d3/df8/mymodule_8css_8php.html", null ],
    [ "mymodule.js.php", "d7/d0f/mymodule_8js_8php.html", null ],
    [ "mymodule.lib.php", "d1/dea/mymodule_8lib_8php.html", null ],
    [ "mymodule_myobject.lib.php", "d1/d9c/mymodule__myobject_8lib_8php.html", null ],
    [ "mymoduleindex.php", "db/d69/mymoduleindex_8php.html", null ],
    [ "myobject_agenda.php", "dc/d65/myobject__agenda_8php.html", null ],
    [ "myobject_card.php", "df/d32/myobject__card_8php.html", null ],
    [ "myobject_contact.php", "df/dfb/myobject__contact_8php.html", null ],
    [ "myobject_document.php", "de/d50/myobject__document_8php.html", null ],
    [ "myobject_list.php", "db/d9c/myobject__list_8php.html", null ],
    [ "myobject_note.php", "dd/df5/myobject__note_8php.html", null ],
    [ "mymodule.php", "dc/d7b/mymodule_8php.html", null ],
    [ "MyModuleFunctionalTest.php", "d1/d53/_my_module_functional_test_8php.html", null ],
    [ "MyObjectTest.php", "df/d9d/_my_object_test_8php.html", null ],
    [ "hook_agenda.php", "dd/d51/hook__agenda_8php.html", null ],
    [ "myobject_note.php", "dd/df5/myobject__note_8php.html", null ],
    [ "mymodule_myobject.lib.php", "d1/d9c/mymodule__myobject_8lib_8php.html", null ]
];