Dolibarr: htdocs/install/inc.php File Reference
inc.php File Reference
File that define environment for support pages.
Functions
conf ($dolibarr_main_document_root)
Load conf file (file must exists)
pHeader ($subtitle, $next, $action='set', $param='', $forcejqueryurl='', $csstable='main-inside')
Show HTML header of install pages.
pFooter ($nonext=0, $setuplang='', $jscheckfunction='', $withpleasewait=0)
Print HTML footer of install pages.
dolibarr_install_syslog ($message, $level=LOG_DEBUG)
Log function for install pages.
detect_dolibarr_main_document_root ()
Automatically detect Dolibarr's main document root.
detect_dolibarr_main_data_root ($dolibarr_main_document_root)
Automatically detect Dolibarr's main data root.
detect_dolibarr_main_url_root ()
Automatically detect Dolibarr's main URL root.
parse_database_login ($force_install_databaserootlogin)
Replaces automatic database login by actual value.
parse_database_pass ($force_install_databaserootpass)
Replaces automatic database password by actual value.
Variables
if (!defined('DOL_INC_FOR_VERSION_ERROR')) define('DOL_INC_FOR_VERSION_ERROR'
$conf = new stdClass()
$conf global = new stdClass()
$conf file = new stdClass()
$conf db = new stdClass()
API class for accounts.
$conf syslog = new stdClass()
$_REQUEST ["logtohtml"] = 1
if(isset($_SERVER["DOCUMENT_URI"]) && $_SERVER["DOCUMENT_URI"]) $includeconferror = ''
$conffiletoshowshort = "conf.php"
$conffile = "../conf/conf.php"
$conffiletoshow = "htdocs/conf/conf.php"
if(!defined('DONOTLOADCONF') &&file_exists($conffile) &&filesize($conffile) > 8) $conf global MAIN_ENABLE_LOG_TO_HTML = 1
const MAIN_DB_PREFIX (isset($dolibarr_main_db_prefix) ? $dolibarr_main_db_prefix : '')
const DOL_CLASS_PATH 'class/'
const DOL_DATA_ROOT (isset($dolibarr_main_data_root) ? $dolibarr_main_data_root : DOL_DOCUMENT_ROOT.'/../documents')
const DOL_MAIN_URL_ROOT (isset($dolibarr_main_url_root) ? $dolibarr_main_url_root : '')
$uri = preg_replace('/^http(s?):\/\//i', '', constant('DOL_MAIN_URL_ROOT'))
$suburi = strstr($uri, '/')
const DOL_URL_ROOT $suburi
$conf file dol_document_root = array(DOL_DOCUMENT_ROOT)
if(!empty($dolibarr_main_document_root_alt)) if(preg_match('/install\.lock/i', $_SERVER["SCRIPT_FILENAME"])) $lockfile = DOL_DATA_ROOT.'/install.lock'
if(constant('DOL_DATA_ROOT')===null) if(@file_exists($lockfile)) $conf syslog enabled = 1
$conf global SYSLOG_LEVEL = constant('LOG_DEBUG')
$handlers = array('mod_syslog_file')
foreach($handlers as $handler) $langs = new Translate('..', $conf)
Detailed Description
File that define environment for support pages.
Definition in file inc.php.
Function Documentation
conf()
conf ($dolibarr_main_document_root)
Load conf file (file must exists)
Parameters
string $dolibarr_main_document_root Root directory of Dolibarr bin files
Returns
int <0 if KO, >0 if OK
Definition at line 268 of file inc.php.
detect_dolibarr_main_data_root()
detect_dolibarr_main_data_root ($dolibarr_main_document_root)
Automatically detect Dolibarr's main data root.
Parameters
string $dolibarr_main_document_root Current main document root
Returns
string
Definition at line 525 of file inc.php.
detect_dolibarr_main_document_root()
detect_dolibarr_main_document_root ()
Automatically detect Dolibarr's main document root.
Returns
string
Definition at line 500 of file inc.php.
detect_dolibarr_main_url_root()
detect_dolibarr_main_url_root ()
Automatically detect Dolibarr's main URL root.
Returns
string
Definition at line 537 of file inc.php.
dolibarr_install_syslog()
dolibarr_install_syslog ($message, $level = LOG_DEBUG)
Log function for install pages.
Parameters
string $message Message
int $level Level of log
Returns
void
Definition at line 489 of file inc.php.
parse_database_login()
parse_database_login ($force_install_databaserootlogin)
Replaces automatic database login by actual value.
Parameters
string $force_install_databaserootlogin Login
Returns
string
Definition at line 572 of file inc.php.
parse_database_pass()
parse_database_pass ($force_install_databaserootpass)
Replaces automatic database password by actual value.
Parameters
string $force_install_databaserootpass Password
Returns
string
Definition at line 583 of file inc.php.
pFooter()
pFooter ($nonext = 0, $setuplang = '', $jscheckfunction = '', $withpleasewait = 0)
Print HTML footer of install pages.
Parameters
integer $nonext 1=No button "Next step", 2=Show button but disabled with a link to enable
string $setuplang Language code
string $jscheckfunction Add a javascript check function
integer $withpleasewait Add also please wait tags
Returns
void
Definition at line 432 of file inc.php.
pHeader()
pHeader ($subtitle, $next, $action = 'set', $param = '', $forcejqueryurl = '', $csstable = 'main-inside')
Show HTML header of install pages.
Parameters
string $subtitle Title
string $next Next
string $action Action code ('set' or 'upgrade')
string $param Param
string $forcejqueryurl Set jquery relative URL (must end with / if defined)
string $csstable Css for table
Returns
void
Definition at line 353 of file inc.php.
Variable Documentation
db
DoliDB db = new stdClass()
API class for accounts.
API class for supplier invoices.
@access protected
Definition at line 54 of file inc.php.
Referenced by GenericObject\__construct(), TaskStats\__construct(), modCashDesk\__construct(), modMargin\__construct(), modWebServices\__construct(), modWebServicesClient\__construct(), modDynamicPrices\__construct(), modGravatar\__construct(), modPayBox\__construct(), modStripe\__construct(), modNotification\__construct(), modDebugBar\__construct(), modECM\__construct(), Auth\__construct(), modGeoIPMaxmind\__construct(), modLdap\__construct(), modPaypal\__construct(), modSyslog\__construct(), modWorkflow\__construct(), modClickToDial\__construct(), modBookmark\__construct(), modExport\__construct(), modFTP\__construct(), modImport\__construct(), modLabel\__construct(), modMailmanSpip\__construct(), ActionsContactCardDefault\__construct(), FormAdmin\__construct(), ActionsAdherentCardDefault\__construct(), modBarcode\__construct(), ActionsCardIndividual\__construct(), Client\__construct(), modDocumentGeneration\__construct(), modExternalSite\__construct(), modFckeditor\__construct(), modMailing\__construct(), ActionsCardCompany\__construct(), modDon\__construct(), modOauth\__construct(), modPrinting\__construct(), modReceiptPrinter\__construct(), InterfaceTicketEmail\__construct(), FormWebsite\__construct(), Utils\__construct(), CdavLib\__construct(), Fournisseur\__construct(), CoreObject\__construct(), FormContract\__construct(), TraceableDB\__construct(), FormCron\__construct(), FormPropal\__construct(), FormIntervention\__construct(), FormSocialContrib\__construct(), FormEcm\__construct(), FormMargin\__construct(), InterfaceStripe\__construct(), FormBank\__construct(), FormActions\__construct(), FormBarCode\__construct(), FormProjets\__construct(), PrintingDriver\__construct(), mailing_advthirdparties\__construct(), mailing_xinputfile\__construct(), mailing_xinputuser\__construct(), Interfaces\__construct(), MenuManager\__construct(), FormProduct\__construct(), PriceParser\__construct(), MailingTargets\__construct(), InterfaceZapierTriggers\__construct(), ExpeditionLineBatch\__construct(), InterfaceMyModuleTriggers\__construct(), FormAccounting\__construct(), FormOther\__construct(), FormFile\__construct(), mailing_pomme\__construct(), ActionsStripeconnect\__construct(), AntiVir\__construct(), mailing_contacts1\__construct(), mailing_example\__construct(), FormResource\__construct(), mailing_fraise\__construct(), ProductCombination2ValuePair\__construct(), ActionsDatapolicy\__construct(), ExtraLanguages\__construct(), Propalmergepdfproduct\__construct(), RssParser\__construct(), ActionsMyModule\__construct(), Canvas\__construct(), CompanyBankAccount\__construct(), CommonDocGenerator\__construct(), Link\__construct(), Productbatch\__construct(), PriceExpression\__construct(), HookManager\__construct(), Ctypent\__construct(), Export\__construct(), MailmanSpip\__construct(), CUnits\__construct(), CActionComm\__construct(), Dolresource\__construct(), PriceGlobalVariable\__construct(), PaymentTerm\__construct(), ProductStockEntrepot\__construct(), Stripe\__construct(), UserBankAccount\__construct(), Cstate\__construct(), Localtax\__construct(), RemiseCheque\__construct(), PaiementFourn\__construct(), Ccountry\__construct(), AccountancySystem\__construct(), FichinterRec\__construct(), PriceGlobalVariableUpdater\__construct(), DolibarrTriggers\__construct(), Tva\__construct(), Productcustomerprice\__construct(), Form\__construct(), FormSms\__construct(), Comment\__construct(), ActionsTicket\__construct(), AccountingJournal\__construct(), Mailing\__construct(), Bookmark\__construct(), AssetType\__construct(), Livraison\__construct(), Notify\__construct(), PaymentExpenseReport\__construct(), PaymentSalary\__construct(), PaymentDonation\__construct(), MultiCurrency\__construct(), PaymentSocialContribution\__construct(), PaymentVarious\__construct(), FormTicket\__construct(), Productlot\__construct(), LoanSchedule\__construct(), EcmFiles\__construct(), PaymentLoan\__construct(), Establishment\__construct(), DiscountAbsolute\__construct(), AdherentType\__construct(), MouvementStock\__construct(), CommandeFournisseurDispatch\__construct(), Opensurveysondage\__construct(), CashControl\__construct(), Loan\__construct(), Cronjob\__construct(), Subscription\__construct(), Reception\__construct(), ChargeSociales\__construct(), Deplacement\__construct(), Events\__construct(), Task\__construct(), Website\__construct(), UserGroup\__construct(), AccountancyCategory\__construct(), Don\__construct(), Paiement\__construct(), FormMail\__construct(), Holiday\__construct(), dolReceiptPrinter\__construct(), Menubase\__construct(), Fichinter\__construct(), BookKeeping\__construct(), ExtraFields\__construct(), FactureRec\__construct(), ExpenseReport\__construct(), WebsitePage\__construct(), Project\__construct(), User\__construct(), Ticket\__construct(), Contrat\__construct(), CommandeFournisseur\__construct(), Adherent\__construct(), FactureFournisseur\__construct(), DolibarrModules\__construct(), ActionComm\__construct(), Commande\__construct(), Facture\__construct(), Product\__construct(), CurrencyRate\__construct(), CommonInvoiceLine\__construct(), LivraisonLigne\__construct(), FichinterLigne\__construct(), AccountLine\__construct(), ExpenseReportLine\__construct(), ExpeditionLigne\__construct(), ContratLigne\__construct(), SupplierProposalLine\__construct(), SupplierInvoiceLine\__construct(), CommandeFournisseurLigne\__construct(), PropaleLigne\__construct(), OrderLine\__construct(), Societe\add_commercial(), MultiCurrency\addRate(), TraceableDB\affected_rows(), DoliDBMysqli\affected_rows(), DoliDBMssql\affected_rows(), DoliDBSqlite3\affected_rows(), TraceableDB\begin(), CommonInvoice\calculate_date_lim_reglement(), CommandeFournisseur\classifyBilled(), Propal\classifyBilled(), Commande\classifyBilled(), Product\clone_associations(), Product\clone_fournisseurs(), DoliDBMssql\close(), DoliDBMysqli\close(), DoliDBSqlite3\close(), DoliDBPgsql\close(), TraceableDB\close(), DolQueryCollector\collect(), Livraison\create_from_sending(), TraceableDB\DDLCreateDb(), TraceableDB\DDLCreateUser(), TraceableDB\DDLGetConnectId(), Fiscalyear\delete(), ChargeSociales\delete(), Loan\delete(), Establishment\delete(), Deplacement\delete(), Link\delete(), ProductStockEntrepot\delete(), Productlot\delete(), Website\delete(), EcmFiles\delete(), Cronjob\delete(), BonPrelevement\delete(), FactureLigneRec\delete(), BookKeeping\deleteByImportkey(), FactureFournisseur\deleteline(), TraceableDB\encrypt(), TraceableDB\errno(), DoliDBSqlite3\errno(), DoliDBPgsql\errno(), TraceableDB\error(), DoliDBMysqli\error(), DoliDBPgsql\error(), TraceableDB\escape(), DoliDBMysqli\escape(), TraceableDB\fetch_array(), TraceableDB\fetch_object(), TraceableDB\fetch_row(), TraceableDB\free(), Products\getAttributes(), TraceableDB\getDefaultCharacterSetDatabase(), TraceableDB\getDefaultCollationDatabase(), DoliDBMysqli\getDriverInfo(), TraceableDB\getDriverInfo(), ActionsTicket\getInstanceDao(), BOM\getLinesArray(), MyObject\getLinesArray(), Mo\getLinesArray(), TraceableDB\getListOfCharacterSet(), TraceableDB\getListOfCollation(), TraceableDB\getPathOfDump(), TraceableDB\getPathOfRestore(), DoliDBMysqli\getVersion(), TraceableDB\getVersion(), TraceableDB\getVersionArray(), TraceableDB\ifsql(), TraceableDB\lasterrno(), TraceableDB\lasterror(), TraceableDB\lastquery(), TraceableDB\lastqueryerror(), TraceableDB\num_rows(), DoliDBSqlite3\num_rows(), Tickets\post(), Tickets\postNewMessage(), TraceableDB\query(), DoliDBMssql\select_db(), DoliDBMysqli\select_db(), TraceableDB\select_db(), Propal\set_availability(), Facture\set_canceled(), Commande\set_date(), Propal\set_date_livraison(), CommandeFournisseur\set_date_livraison(), Commande\set_date_livraison(), Propal\set_demand_reason(), Propal\set_echeance(), CommandeFournisseur\set_id_projet(), Facture\set_paid(), Propal\set_ref_client(), Commande\set_ref_client(), Commande\set_remise(), Facture\set_remise(), Propal\set_remise_absolue(), Commande\set_remise_absolue(), Facture\set_remise_absolue(), Propal\set_remise_percent(), Facture\set_unpaid(), CompanyBankAccount\setAsDefault(), CompanyPaymentMode\setAsDefault(), Facture\setFinal(), Facture\setRetainedWarrantyDateLimit(), BookKeeping\transformTransaction(), AccountingAccount\update(), Loan\update(), ChargeSociales\update(), AccountLine\update(), User\update_clicktodial(), Adherent\update_end_date(), ContratLigne\update_total(), SupplierProposalLine\update_total(), SupplierInvoiceLine\update_total(), PropaleLigne\update_total(), OrderLine\update_total(), FactureLigne\update_total(), Holiday\updateBalance(), and CommandeFournisseur\updateFromCommandeClient().