Dolibarr: htdocs/compta/index.php File Reference
index.php File Reference
Main page of accountancy area.
Variables
$action = GETPOST('action', 'aZ09')
$bid = GETPOST('bid', 'int')
$socid = ''
if($user->socid > 0) $max = $conf->global->MAIN_SIZE_SHORTLIST_LIMIT
$now = dol_now()
$form = new Form($db)
$formfile = new FormFile($db)
$thirdpartystatic = new Societe($db)
print
Draft customers invoices.
if(!empty($conf->facture->enabled) && $user->rights->facture->lire) if((!empty($conf->fournisseur->enabled) &&empty($conf->global->MAIN_USE_NEW_SUPPLIERMOD)||!empty($conf->supplier_invoice->enabled)) && $user->rights->fournisseur->facture->lire) if(!empty($conf->don->enabled) && $user->rights->don->lire) if(!empty($conf->tax->enabled) && $user->rights->tax->charges->lire) if(!empty($conf->facture->enabled) &&!empty($conf->commande->enabled) && $user->rights->commande->lire &&empty($conf->global->WORKFLOW_DISABLE_CREATE_INVOICE_FROM_ORDER)) if(!empty($conf->facture->enabled) && $user->rights->facture->lire) if((!empty($conf->fournisseur->enabled) &&empty($conf->global->MAIN_USE_NEW_SUPPLIERMOD)||!empty($conf->supplier_invoice->enabled)) && $user->rights->fournisseur->facture->lire) $resql = 0
Social contributions to pay.
$parameters = array('user' => $user)
$reshook = $hookmanager->executeHooks('dashboardAccountancy', $parameters, $object)
Detailed Description
Main page of accountancy area.
Definition in file index.php.
Variable Documentation
print
if ($resql) print
Draft customers invoices.
Draft suppliers invoices
Definition at line 89 of file index.php.
Referenced by dol_fiche_end(), dol_set_focus(), AccountancyExport\exportSAGE50SWISS(), llxFooter(), llxFooterSurvey(), llxFooterVierge(), llxHeader(), llxHeaderVierge(), print_end_menu_array(), print_end_menu_array_auguria(), print_end_menu_array_empty(), print_end_menu_entry(), print_end_menu_entry_auguria(), print_end_menu_entry_empty(), FormMail\show_form(), and MyObjectTest\tearDown().