Dolibarr: Societe Class Reference
Societe Class Reference
Class to manage third parties objects (customers, suppliers, prospects...)
Public Member Functions
__construct ($db)
Constructor.
create (User $user)
Create third party in database.
create_individual (User $user)
Create a contact/address from thirdparty.
verify ()
Check properties of third party are ok (like name, third party codes, ...) Used before an add or update.
update ($id, $user='', $call_trigger=1, $allowmodcodeclient=0, $allowmodcodefournisseur=0, $action='update', $nosyncmember=1)
Update parameters of third party.
fetch ($rowid, $ref='', $ref_ext='', $notused='', $idprof1='', $idprof2='', $idprof3='', $idprof4='', $idprof5='', $idprof6='', $email='', $ref_alias='')
Load a third party from database into memory.
delete ($id, User $fuser=null, $call_trigger=1)
Delete a third party from database and all its dependencies (contacts, rib...)
set_as_client ()
Define third party as a customer.
set_remise_client ($remise, $note, User $user)
Defines the company as a customer.
set_remise_supplier ($remise, $note, User $user)
Defines the company as a customer.
set_remise_except ($remise, User $user, $desc, $vatrate='', $discount_type=0)
Add a discount for third party.
getAvailableDiscounts ($user='', $filter='', $maxvalue=0, $discount_type=0)
Returns amount of included taxes of the current discounts/credits available from the company.
getSalesRepresentatives (User $user, $mode=0)
Return array of sales representatives.
set_price_level ($price_level, User $user)
Set the price level.
add_commercial (User $user, $commid)
Add link to sales representative.
del_commercial (User $user, $commid)
Add link to sales representative.
getNomUrl ($withpicto=0, $option='', $maxlen=0, $notooltip=0, $save_lastsearch_value=-1)
Return a link on thirdparty (with picto)
getLibStatut ($mode=0)
Return label of status (activity, closed)
LibStatut ($status, $mode=0)
Return the label of a given status.
thirdparty_and_contact_email_array ($addthirdparty=0)
Return list of contacts emails existing for third party.
thirdparty_and_contact_phone_array ()
Return list of contacts mobile phone existing for third party.
contact_property_array ($mode='email', $hidedisabled=0)
Return list of contacts emails or mobile existing for third party.
contact_array ()
Returns the contact list of this company.
contact_array_objects ()
Returns the contact list of this company.
contact_get_property ($rowid, $mode)
Return property of contact from its id.
display_rib ($mode='label')
Return bank number property of thirdparty (label or rum)
get_all_rib ()
Return Array of RIB.
get_codeclient ($objsoc=0, $type=0)
Assigns a customer code from the code control module.
get_codefournisseur ($objsoc=0, $type=1)
Assigns a vendor code from the code control module.
codeclient_modifiable ()
Check if a client code is editable based on the parameters of the code control module.
codefournisseur_modifiable ()
Check if a vendor code is editable in the code control module configuration.
check_codeclient ()
Check customer code.
check_codefournisseur ()
Check supplier code.
get_codecompta ($type)
Assigns a accounting code from the accounting code module.
set_parent ($id)
Define parent commany of current company.
id_prof_verifiable ($idprof)
Returns if a profid sould be verified.
id_prof_exists ($idprof, $value, $socid=0)
Verify if a profid exists into database for others thirds.
id_prof_check ($idprof, $soc)
Check the validity of a professional identifier according to the country of the company (siren, siret, ...)
id_prof_url ($idprof, $thirdparty)
Return an url to check online a professional id or empty string.
has_projects ()
Indicates if the company has projects.
info ($id)
Load information for tab info.
isACompany ()
Return if third party is a company (Business) or an end user (Consumer)
isInEEC ()
Return if a company is inside the EEC (European Economic Community)
LoadSupplierCateg ()
Load the list of provider categories.
AddFournisseurInCategory ($categorie_id)
Insert link supplier - category.
create_from_member (Adherent $member, $socname='', $socalias='', $customercode='')
Create a third party into database from a member object.
setMysoc (Conf $conf)
Set properties with value into $conf.
initAsSpecimen ()
Initialise an instance with random values.
useLocalTax ($localTaxNum=0)
Check if we must use localtax feature or not according to country (country of $mysoc in most cases).
useNPR ()
Check if we must use NPR Vat (french stupid rule) or not according to country (country of $mysoc in most cases).
useRevenueStamp ()
Check if we must use revenue stamps feature or not according to country (country of $mysocin most cases).
getLibProspLevel ()
Return prostect level.
LibProspLevel ($fk_prospectlevel)
Return label of prospect level.
set_prospect_level (User $user)
Set prospect level.
getLibProspCommStatut ($mode=0, $label='')
Return status of prospect.
LibProspCommStatut ($status, $mode=0, $label='')
Return label of a given status.
set_OutstandingBill (User $user)
Set outstanding value.
getOutstandingProposals ($mode='customer')
Return amount of order not paid and total.
getOutstandingOrders ($mode='customer')
Return amount of order not paid and total.
getOutstandingBills ($mode='customer')
Return amount of bill not paid and total.
getLibCustProspStatut ()
Return label of status customer is prospect/customer.
LibCustProspStatut ($status)
Return the label of the customer/prospect status.
generateDocument ($modele, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0, $moreparams=null)
Create a document onto disk according to template module.
setCategories ($categories, $type_categ)
Sets object to supplied categories.
setSalesRep ($salesrep, $onlyAdd=false)
Sets sales representatives of the thirdparty.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
getKanbanView ($option='')
Return clicable link of object (with eventually picto)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0, $extralangcode='')
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source='external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source='internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source='', $code='')
Delete all links between an object $this and all its contacts.
liste_contact ($status=-1, $source='external', $list=0, $code='')
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source='internal', $order='position', $option=0, $activeonly=0, $code='')
Return array with list of possible values for type of contacts.
listeTypeContacts ($source='internal', $option=0, $activeonly=0, $code='', $element='', $excludeelement='')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contactid into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table='', $id=null, $format='', $id_field='', $fuser=null, $trigkey='', $fk_user_field='fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source='external')
Return list of id of contacts of object.
setProject ($projectid)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id)
Change the payments terms.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder='ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix='')
Update note of element.
update_note_public ($note)
update_price ($exclspec=0, $roundingadjust='none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null)
Add objects linked in llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $clause='OR', $alsosametype=1, $orderby='sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
updateObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='')
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $rowid='')
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType='', $trigkey='')
Set status of an object.
getCanvas ($id=0, $ref='')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
display_incoterms ()
Return incoterms informations TODO Use a cache for label get.
getIncotermsForPDF ()
Return incoterms informations for pdf display.
setIncoterms ($id_incoterm, $location)
Define incoterms values of current object.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir='/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir='/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafields=null, $defaulttpldir='/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist='', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist='', $defaulttpldir='/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
addThumbs ($file)
Build thumb.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($triggerName, $user)
Call trigger based on this instance.
fetchValuesForExtraLanguages ()
Function to get alternative languages of a data into $this->array_languages This method is NOT called by method fetch of objects but must be called separately.
setValuesForExtraLanguages ($onlykey='')
Fill array_options property of object by extrafields value (using for data sent by forms)
fetchNoCompute ($id)
Function to make a fetch but set environment to avoid to load computed values before.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
insertExtraLanguages ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update an extra field value for the current object.
updateExtraLanguages ($key, $trigger=null, $userused=null)
Update an extra language value for the current object.
showInputField ($val, $key, $value, $moreparam='', $keysuffix='', $keyprefix='', $morecss=0, $nonewbutton=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
showOutputField ($val, $key, $value, $moreparam='', $keysuffix='', $keyprefix='', $morecss='')
Return HTML string to show a field into a page Code very similar with showOutputField of extra fields.
showOptionals ($extrafields, $mode='view', $params=null, $keysuffix='', $keyprefix='', $onetrtd=0)
Function to show lines of extrafields with output datas.
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isDuration ($info)
Function test if type is duration.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere='')
Load object in memory from the database.
fetchLinesCommon ($morewhere='')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteByParentField ($parentId=0, $parentField='')
Delete all child object from a parent ID.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
setStatusCommon ($user, $status, $notrigger=0, $triggercode='')
Set to a status.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
cloneCategories ($fromId, $toId, $type='')
copy related categories to another object
deleteEcmFiles ()
Delete related files of object in database.
Static Public Member Functions
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id)
Function used to replace a thirdparty id with another one.
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref='', $ref_ext='')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static commonReplaceThirdparty (DoliDB $db, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
Public Attributes
$element = 'societe'
$table_element = 'societe'
$fk_element = 'fk_soc'
$fieldsforcombobox = 'nom,name_alias'
$picto = 'company'
$ismultientitymanaged = 1
$restrictiononfksoc = 1
$fields
$entity
$nom
$name
$name_alias
$particulier
$address
$zip
$town
$status = 1
$state_id
$state_code
$state
$region_code
$region
$departement_code
$departement
$pays
$phone
$fax
$email
$socialnetworks
$skype
$twitter
$facebook
$linkedin
$url
$barcode
$idprof1
$idprof2
$idprof3
$idprof4
$idprof5
$idprof6
$prefix_comm
$tva_assuj = 1
$tva_intra
$localtax1_assuj
$localtax1_value
$localtax2_assuj
$localtax2_value
$managers
$capital
$typent_id = 0
$typent_code
$effectif
$effectif_id = 0
$forme_juridique_code
$forme_juridique = 0
$remise_percent
$remise_supplier_percent
$mode_reglement_supplier_id
$cond_reglement_supplier_id
$fk_prospectlevel
$name_bis
$date_modification
$user_modification
$date_creation
$user_creation
$specimen
$client = 0
$prospect = 0
$fournisseur
$code_client
$code_fournisseur
$code_compta
$code_compta_client
$code_compta_fournisseur
$note
$note_private
$note_public
$stcomm_id
$status_prospect_label
$price_level
$outstanding_limit
$order_min_amount
$supplier_order_min_amount
$commercial_id
$parent
$default_lang
$ref
$ref_int
$ref_ext
$import_key
$webservices_url
$webservices_key
$logo
$logo_small
$logo_mini
$logo_squarred
$logo_squarred_small
$logo_squarred_mini
$fk_incoterms
$location_incoterms
$label_incoterms
$fk_multicurrency
$multicurrency_code
$bank_account
Public Attributes inherited from CommonObject
$db
$id
$error
$errors = array()
$element
$table_element
$table_element_line = ''
$import_key
$array_options = array()
$array_languages = null
$linkedObjectsIds
$linkedObjects
$oldcopy
$context = array()
$canvas
$project
$fk_project
$projet
$contact
$contact_id
$thirdparty
$user
$origin
$origin_id
$ref
$ref_previous
$ref_next
$ref_ext
$statut
$country
$country_id
$country_code
$state
$state_id
$state_code
$region
$region_code
$barcode_type
$barcode_type_code
$barcode_type_label
$barcode_type_coder
$mode_reglement_id
$cond_reglement_id
$cond_reglement
$fk_delivery_address
$shipping_method_id
$modelpdf
$last_main_doc
$fk_account
$note_public
$note_private
$note
$total_ht
$total_tva
$total_localtax1
$total_localtax2
$total_ttc
$lines
$comments = array()
$fk_incoterms
$label_incoterms
$location_incoterms
$name
$lastname
$firstname
$civility_id
$date_creation
$date_validation
$date_modification
$next_prev_filter
Protected Attributes
$childtables
$childtablesoncascade
Protected Attributes inherited from CommonObject
$table_ref_field = ''
$childtables = array()
$childtablesoncascade = array()
Additional Inherited Members
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
canBeNull ($info)
Function test if field can be null.
isForcedToNullIfZero ($info)
Function test if field is forced to null if zero or empty.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare a part of the query for insert.
getFieldList ()
Function to concat keys of fields.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage third parties objects (customers, suppliers, prospects...)
Definition at line 45 of file societe.class.php.
Constructor & Destructor Documentation
__construct()
__construct ($db)
Constructor.
Parameters
DoliDB $db Database handler
Reimplemented in Fournisseur, and Client.
Definition at line 726 of file societe.class.php.
Member Function Documentation
add_commercial()
add_commercial (User $user, $commid)
Add link to sales representative.
Parameters
User $user Object user
int $commid Id of user
Returns
int <=0 if KO, >0 if OK
Definition at line 2236 of file societe.class.php.
References db.
AddFournisseurInCategory()
AddFournisseurInCategory ($categorie_id)
Insert link supplier - category.
Parameters
int $categorie_id Id of category
Returns
int 0 if success, <> 0 if error
Definition at line 3626 of file societe.class.php.
check_codeclient()
check_codeclient ()
Check customer code.
Returns
int 0 if OK -1 ErrorBadCustomerCodeSyntax -2 ErrorCustomerCodeRequired -3 ErrorCustomerCodeAlreadyUsed -4 ErrorPrefixRequired -5 NotConfigured - Setup empty so any value may be ok or not -6 Other (see this->error)
Definition at line 3024 of file societe.class.php.
check_codefournisseur()
check_codefournisseur ()
Check supplier code.
Returns
int 0 if OK -1 ErrorBadCustomerCodeSyntax -2 ErrorCustomerCodeRequired -3 ErrorCustomerCodeAlreadyUsed -4 ErrorPrefixRequired -5 NotConfigured - Setup empty so any value may be ok or not -6 Other (see this->error)
Definition at line 3063 of file societe.class.php.
codeclient_modifiable()
codeclient_modifiable ()
Check if a client code is editable based on the parameters of the code control module.
Returns
int 0=No, 1=Yes
Definition at line 2946 of file societe.class.php.
codefournisseur_modifiable()
codefournisseur_modifiable ()
Check if a vendor code is editable in the code control module configuration.
Returns
int 0=No, 1=Yes
Definition at line 2982 of file societe.class.php.
contact_array()
contact_array ()
Returns the contact list of this company.
Returns
array array of contacts
Definition at line 2699 of file societe.class.php.
contact_array_objects()
contact_array_objects ()
Returns the contact list of this company.
Returns
array $contacts array of contacts
Definition at line 2733 of file societe.class.php.
contact_get_property()
contact_get_property ($rowid, $mode)
Return property of contact from its id.
Parameters
int $rowid id of contact
string $mode 'email' or 'mobile'
Returns
string Email of contact with format: "Full name <email>"
Definition at line 2772 of file societe.class.php.
contact_property_array()
contact_property_array ($mode = 'email', $hidedisabled = 0)
Return list of contacts emails or mobile existing for third party.
Parameters
string $mode 'email' or 'mobile'
int $hidedisabled 1=Hide contact if disabled
Returns
array Array of contacts emails or mobile. Example: array(id=>'Name <email>')
Definition at line 2630 of file societe.class.php.
create()
create (User $user)
Create third party in database.
$this->code_client = -1 and $this->code_fournisseur = -1 means automatic assignement.
Parameters
User $user Object of user that ask creation
Returns
int >= 0 if OK, < 0 if KO
Definition at line 757 of file societe.class.php.
create_from_member()
create_from_member (Adherent $member, $socname = '', $socalias = '', $customercode = '')
Create a third party into database from a member object.
Parameters
Adherent $member Object member
string $socname Name of third party to force
string $socalias Alias name of third party to force
string $customercode Customer code
Returns
int <0 if KO, id of created account if OK
Definition at line 3654 of file societe.class.php.
create_individual()
create_individual (User $user)
Create a contact/address from thirdparty.
Parameters
User $user Object user
Returns
int <0 if KO, >0 if OK
Definition at line 885 of file societe.class.php.
del_commercial()
del_commercial (User $user, $commid)
Add link to sales representative.
Parameters
User $user Object user
int $commid Id of user
Returns
void
Definition at line 2306 of file societe.class.php.
delete()
delete ($id, User $fuser = null, $call_trigger = 1)
Delete a third party from database and all its dependencies (contacts, rib...)
Parameters
int $id Id of third party to delete
User $fuser User who ask to delete thirdparty
int $call_trigger 0=No, 1=yes
Returns
int <0 if KO, 0 if nothing done, >0 if OK
Definition at line 1721 of file societe.class.php.
display_rib()
display_rib ($mode = 'label')
Return bank number property of thirdparty (label or rum)
Parameters
string $mode 'label' or 'rum' or 'format'
Returns
string Bank label or RUM or '' if no bank account found
Definition at line 2811 of file societe.class.php.
fetch()
fetch ($rowid, $ref = '', $ref_ext = '', $notused = '', $idprof1 = '', $idprof2 = '', $idprof3 = '', $idprof4 = '', $idprof5 = '', $idprof6 = '', $email = '', $ref_alias = '')
Load a third party from database into memory.
Parameters
int $rowid Id of third party to load
string $ref Reference of third party, name (Warning, this can return several records)
string $ref_ext External reference of third party (Warning, this information is a free field not provided by Dolibarr)
string $notused Not used
string $idprof1 Prof id 1 of third party (Warning, this can return several records)
string $idprof2 Prof id 2 of third party (Warning, this can return several records)
string $idprof3 Prof id 3 of third party (Warning, this can return several records)
string $idprof4 Prof id 4 of third party (Warning, this can return several records)
string $idprof5 Prof id 5 of third party (Warning, this can return several records)
string $idprof6 Prof id 6 of third party (Warning, this can return several records)
string $email Email of third party (Warning, this can return several records)
string $ref_alias Name_alias of third party (Warning, this can return several records)
Returns
int >0 if OK, <0 if KO or if two records found for same ref or idprof, 0 if not found.
Definition at line 1492 of file societe.class.php.
generateDocument()
generateDocument ($modele, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0, $moreparams = null)
Create a document onto disk according to template module.
Parameters
string $modele Generator to use. Caller must set it to obj->modelpdf or GETPOST('modelpdf','alpha') for example.
Translate $outputlangs objet lang a utiliser pour traduction
int $hidedetails Hide details of lines
int $hidedesc Hide description
int $hideref Hide ref
null | array $moreparams Array to provide more information
Returns
int <0 if KO, >0 if OK
Definition at line 4312 of file societe.class.php.
get_all_rib()
get_all_rib ()
Return Array of RIB.
Returns
array|int 0 if KO, Array of CompanyBanckAccount if OK
Definition at line 2852 of file societe.class.php.
get_codeclient()
get_codeclient ($objsoc = 0, $type = 0)
Assigns a customer code from the code control module.
Return value is stored into this->code_client
Parameters
Societe $objsoc Object thirdparty
int $type Should be 0 to say customer
Returns
void
Definition at line 2885 of file societe.class.php.
get_codecompta()
get_codecompta ($type)
Assigns a accounting code from the accounting code module.
Computed value is stored into this->code_compta or this->code_compta_fournisseur according to $type. May be identical to the one entered or generated automatically. Currently, only the automatic generation is implemented.
Parameters
string $type Type of thirdparty ('customer' or 'supplier')
Returns
int 0 if OK, <0 if $type is not valid
Definition at line 3099 of file societe.class.php.
get_codefournisseur()
get_codefournisseur ($objsoc = 0, $type = 1)
Assigns a vendor code from the code control module.
Return value is stored into this->code_fournisseur
Parameters
Societe $objsoc Object thirdparty
int $type Should be 1 to say supplier
Returns
void
Definition at line 2917 of file societe.class.php.
getAvailableDiscounts()
getAvailableDiscounts ($user = '', $filter = '', $maxvalue = 0, $discount_type = 0)
Returns amount of included taxes of the current discounts/credits available from the company.
Parameters
User $user Filter on a user author of discounts
string $filter Other filter
integer $maxvalue Filter on max value for discount
int $discount_type 0 => customer discount, 1 => supplier discount
Returns
int <0 if KO, Credit note amount otherwise
Definition at line 2108 of file societe.class.php.
getLibCustProspStatut()
getLibCustProspStatut ()
Return label of status customer is prospect/customer.
Returns
string Label
Definition at line 4276 of file societe.class.php.
References LibCustProspStatut().
getLibProspCommStatut()
getLibProspCommStatut ($mode = 0, $label = '')
Return status of prospect.
Parameters
int $mode 0=libelle long, 1=libelle court, 2=Picto + Libelle court, 3=Picto, 4=Picto + Libelle long
string $label Label to use for status for added status
Returns
string Libelle
Definition at line 4035 of file societe.class.php.
getLibProspLevel()
getLibProspLevel ()
Return prostect level.
Returns
string Libelle
Definition at line 3987 of file societe.class.php.
References LibProspLevel().
getLibStatut()
getLibStatut ($mode = 0)
Return label of status (activity, closed)
Parameters
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto, 6=Long label + Picto
Returns
string Label of status
Definition at line 2545 of file societe.class.php.
getNomUrl()
getNomUrl ($withpicto = 0, $option = '', $maxlen = 0, $notooltip = 0, $save_lastsearch_value = -1)
Return a link on thirdparty (with picto)
Parameters
int $withpicto Add picto into link (0=No picto, 1=Include picto with link, 2=Picto only)
string $option Target of link ('', 'customer', 'prospect', 'supplier', 'project')
int $maxlen Max length of name
int $notooltip 1=Disable tooltip
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
Returns
string String with URL
Definition at line 2338 of file societe.class.php.
getOutstandingBills()
getOutstandingBills ($mode = 'customer')
Return amount of bill not paid and total.
Parameters
string $mode 'customer' or 'supplier'
Returns
array array('opened'=>Amount, 'total'=>Total amount)
Definition at line 4195 of file societe.class.php.
getOutstandingOrders()
getOutstandingOrders ($mode = 'customer')
Return amount of order not paid and total.
Parameters
string $mode 'customer' or 'supplier'
Returns
array array('opened'=>Amount, 'total'=>Total amount)
Definition at line 4155 of file societe.class.php.
getOutstandingProposals()
getOutstandingProposals ($mode = 'customer')
Return amount of order not paid and total.
Parameters
string $mode 'customer' or 'supplier'
Returns
array array('opened'=>Amount, 'total'=>Total amount)
Definition at line 4115 of file societe.class.php.
getSalesRepresentatives()
getSalesRepresentatives (User $user, $mode = 0)
Return array of sales representatives.
Parameters
User $user Object user
int $mode 0=Array with properties, 1=Array of id.
Returns
array Array of sales representatives of third party
Definition at line 2132 of file societe.class.php.
has_projects()
has_projects ()
Indicates if the company has projects.
Returns
bool true if the company has projects, false otherwise
Definition at line 3485 of file societe.class.php.
id_prof_check()
id_prof_check ($idprof, $soc)
Check the validity of a professional identifier according to the country of the company (siren, siret, ...)
Parameters
int $idprof 1,2,3,4 (Exemple: 1=siren,2=siret,3=naf,4=rcs/rm)
Societe $soc Objet societe
Returns
int <=0 if KO, >0 if OK TODO better to have this in a lib than into a business class
Definition at line 3280 of file societe.class.php.
id_prof_exists()
id_prof_exists ($idprof, $value, $socid = 0)
Verify if a profid exists into database for others thirds.
Parameters
string $idprof 'idprof1','idprof2','idprof3','idprof4','idprof5','idprof6','email' (Example: idprof1=siren, idprof2=siret, idprof3=naf, idprof4=rcs/rm)
string $value Value of profid
int $socid Id of thirdparty to exclude (if update)
Returns
boolean True if exists, False if not
Definition at line 3220 of file societe.class.php.
id_prof_url()
id_prof_url ($idprof, $thirdparty)
Return an url to check online a professional id or empty string.
Parameters
int $idprof 1,2,3,4 (Example: 1=siren,2=siret,3=naf,4=rcs/rm)
Societe $thirdparty Object thirdparty
Returns
string Url or empty string if no URL known TODO better in a lib than into business class
Definition at line 3434 of file societe.class.php.
id_prof_verifiable()
id_prof_verifiable ($idprof)
Returns if a profid sould be verified.
Parameters
int $idprof 1,2,3,4,5,6 (Exemple: 1=siren,2=siret,3=naf,4=rcs/rm,5=idprof5,6=idprof6)
Returns
boolean true , false
Definition at line 3179 of file societe.class.php.
info()
info ($id)
Load information for tab info.
Parameters
int $id Id of thirdparty to load
Returns
void
Definition at line 3511 of file societe.class.php.
initAsSpecimen()
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
int >0 if ok
Definition at line 3860 of file societe.class.php.
isACompany()
isACompany ()
Return if third party is a company (Business) or an end user (Consumer)
Returns
boolean true=is a company, false=a and user
Definition at line 3557 of file societe.class.php.
isInEEC()
isInEEC ()
Return if a company is inside the EEC (European Economic Community)
Returns
boolean true = country inside EEC, false = country outside EEC
Definition at line 3584 of file societe.class.php.
LibCustProspStatut()
LibCustProspStatut ($status)
Return the label of the customer/prospect status.
Parameters
int $status Id of prospection status
Returns
string Label of prospection status
Definition at line 4288 of file societe.class.php.
Referenced by getLibCustProspStatut().
LibProspCommStatut()
LibProspCommStatut ($status, $mode = 0, $label = '')
Return label of a given status.
Parameters
int | string $status Id or code for prospection status
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto
string $label Label to use for status for added status
Returns
string Label of prospection status
Definition at line 4049 of file societe.class.php.
LibProspLevel()
LibProspLevel ($fk_prospectlevel)
Return label of prospect level.
Parameters
int $fk_prospectlevel Prospect level
Returns
string label of level
Definition at line 3999 of file societe.class.php.
Referenced by getLibProspLevel().
LibStatut()
LibStatut ($status, $mode = 0)
Return the label of a given status.
Parameters
int $status Status id
int $mode 0=Long label, 1=Short label, 2=Picto + Short label, 3=Picto, 4=Picto + Long label, 5=Short label + Picto, 6=Long label + Picto
Returns
string Status label
Definition at line 2558 of file societe.class.php.
LoadSupplierCateg()
LoadSupplierCateg ()
Load the list of provider categories.
Returns
int 0 if success, <> 0 if error
Definition at line 3596 of file societe.class.php.
replaceThirdparty()
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id) static
Function used to replace a thirdparty id with another one.
It must be used within a transaction to avoid trouble
Parameters
DoliDB $db Database handler
int $origin_id Old thirdparty id (will be removed)
int $dest_id New thirdparty id
Returns
bool True if success, False if error
Thirdparty commercials cannot be the same in both thirdparties so we look for them and remove some to avoid duplicate. Because this function is meant to be executed within a transaction, we won't take care of begin/commit.
llx_societe_extrafields table must not be here because we don't care about the old thirdparty data Do not include llx_societe because it will be replaced later
Definition at line 4484 of file societe.class.php.
References dol_syslog().
set_as_client()
set_as_client ()
Define third party as a customer.
Returns
int <0 if KO, >0 if OK
Definition at line 1878 of file societe.class.php.
set_OutstandingBill()
set_OutstandingBill (User $user)
Set outstanding value.
Parameters
User $user User making change
Returns
int <0 if KO, >0 if OK
Deprecated:
Use update function instead
Definition at line 4103 of file societe.class.php.
References update().
set_parent()
set_parent ($id)
Define parent commany of current company.
Parameters
int $id Id of thirdparty to set or '' to remove
Returns
int <0 if KO, >0 if OK
Definition at line 3149 of file societe.class.php.
set_price_level()
set_price_level ($price_level, User $user)
Set the price level.
Parameters
int $price_level Level of price
User $user Use making change
Returns
int <0 if KO, >0 if OK
Definition at line 2197 of file societe.class.php.
set_prospect_level()
set_prospect_level (User $user)
Set prospect level.
Parameters
User $user User who sets the discount
Returns
int <0 if KO, >0 if OK
Deprecated:
Use update function instead
Definition at line 4022 of file societe.class.php.
References update().
set_remise_client()
set_remise_client ($remise, $note, User $user)
Defines the company as a customer.
Parameters
float $remise Value in % of the discount
string $note Note/Reason for changing the discount
User $user User who sets the discount
Returns
int <0 if KO, >0 if OK
Definition at line 1909 of file societe.class.php.
set_remise_except()
set_remise_except ($remise, User $user, $desc, $vatrate = '', $discount_type = 0)
Add a discount for third party.
Parameters
float $remise Amount of discount
User $user User adding discount
string $desc Reason of discount
string $vatrate VAT rate (may contain the vat code too). Exemple: '1.23', '1.23 (ABC)', ...
int $discount_type 0 => customer discount, 1 => supplier discount
Returns
int <0 if KO, id of discount record if OK
Definition at line 2037 of file societe.class.php.
set_remise_supplier()
set_remise_supplier ($remise, $note, User $user)
Defines the company as a customer.
Parameters
float $remise Value in % of the discount
string $note Note/Reason for changing the discount
User $user User who sets the discount
Returns
int <0 if KO, >0 if OK
Definition at line 1972 of file societe.class.php.
setCategories()
setCategories ($categories, $type_categ)
Sets object to supplied categories.
Deletes object from existing categories not supplied. Adds it to non existing supplied categories. Existing categories are left untouch.
Parameters
int[] | int $categories Category ID or array of Categories IDs
string $type_categ Category type ('customer' or 'supplier')
Returns
int <0 if KO, >0 if OK
Definition at line 4373 of file societe.class.php.
setMysoc()
setMysoc (Conf $conf)
Set properties with value into $conf.
Parameters
Conf $conf Conf object (possibility to use another entity)
Returns
void
Definition at line 3741 of file societe.class.php.
setSalesRep()
setSalesRep ($salesrep, $onlyAdd = false)
Sets sales representatives of the thirdparty.
Parameters
int[] | int $salesrep User ID or array of user IDs
bool $onlyAdd Only add (no delete before)
Returns
int <0 if KO, >0 if OK
Definition at line 4433 of file societe.class.php.
thirdparty_and_contact_email_array()
thirdparty_and_contact_email_array ($addthirdparty = 0)
Return list of contacts emails existing for third party.
Parameters
int $addthirdparty 1=Add also a record for thirdparty email
Returns
array Array of contacts emails
Definition at line 2585 of file societe.class.php.
thirdparty_and_contact_phone_array()
thirdparty_and_contact_phone_array ()
Return list of contacts mobile phone existing for third party.
Returns
array Array of contacts emails
Definition at line 2606 of file societe.class.php.
update()
update ($id, $user = '', $call_trigger = 1, $allowmodcodeclient = 0, $allowmodcodefournisseur = 0, $action = 'update', $nosyncmember = 1)
Update parameters of third party.
Parameters
int $id Id of company (deprecated, use 0 here and call update on an object loaded by a fetch)
User $user User who requests the update
int $call_trigger 0=no, 1=yes
int $allowmodcodeclient Inclut modif code client et code compta
int $allowmodcodefournisseur Inclut modif code fournisseur et code compta fournisseur
string $action 'add' or 'update' or 'merge'
int $nosyncmember Do not synchronize info of linked member
Returns
int <0 if KO, >=0 if OK
Definition at line 1070 of file societe.class.php.
Referenced by set_OutstandingBill(), and set_prospect_level().
useLocalTax()
useLocalTax ($localTaxNum = 0)
Check if we must use localtax feature or not according to country (country of $mysoc in most cases).
Parameters
int $localTaxNum To get info for only localtax1 or localtax2
Returns
boolean true or false
Definition at line 3916 of file societe.class.php.
useNPR()
useNPR ()
Check if we must use NPR Vat (french stupid rule) or not according to country (country of $mysoc in most cases).
Returns
boolean true or false
Definition at line 3939 of file societe.class.php.
useRevenueStamp()
useRevenueStamp ()
Check if we must use revenue stamps feature or not according to country (country of $mysocin most cases).
Table c_revenuestamp contains the country and value of stamp per invoice.
Returns
boolean true or false
Definition at line 3961 of file societe.class.php.
verify()
verify ()
Check properties of third party are ok (like name, third party codes, ...) Used before an add or update.
Returns
int 0 if OK, <0 if KO
Definition at line 923 of file societe.class.php.
Member Data Documentation
$childtables
$childtables protected
Initial value:
= array(
        "supplier_proposal" => 'SupplierProposal',
        "propal" => 'Proposal',
        "commande" => 'Order',
        "facture" => 'Invoice',
        "facture_rec" => 'RecurringInvoiceTemplate',
        "contrat" => 'Contract',
        "fichinter" => 'Fichinter',
        "facture_fourn" => 'SupplierInvoice',
        "commande_fournisseur" => 'SupplierOrder',
        "projet" => 'Project',
        "expedition" => 'Shipment',
        "prelevement_lignes" => 'DirectDebitRecord',
    )
Definition at line 70 of file societe.class.php.
$childtablesoncascade
$childtablesoncascade protected
Initial value:
= array(
        "societe_prices",
        "societe_address",
        "product_fournisseur_price",
        "product_customer_price_log",
        "product_customer_price",
        "@Contact:/contact/class/contact.class.php:fk_soc",
        "adherent",
        "societe_account",
        "societe_rib",
        "societe_remise",
        "societe_remise_except",
        "societe_commerciaux",
        "categorie",
        "notify",
        "notify_def",
        "actioncomm",
    )
Definition at line 89 of file societe.class.php.
The documentation for this class was generated from the following file:
htdocs/societe/class/societe.class.php