Dolibarr: htdocs/support/inc.php File Reference
inc.php File Reference
File that define environment for support pages.
Functions
conf ($dolibarr_main_document_root)
Load conf file (file must exists)
pHeader ($soutitre, $next, $action='none')
Show HTML header.
pFooter ($nonext=0, $setuplang='')
Print HTML footer.
Variables
if (!defined('DOL_DOCUMENT_ROOT'))
$conf = new stdClass()
$conf global = new stdClass()
$conf file = new stdClass()
$conf db = new stdClass()
API class for accounts.
$conf syslog = new stdClass()
$_REQUEST ["logtohtml"] = 1
if(isset($_SERVER["DOCUMENT_URI"]) && $_SERVER["DOCUMENT_URI"]) $includeconferror = ''
$conffiletoshowshort = "conf.php"
$conffile = "../conf/conf.php"
$conffiletoshow = "htdocs/conf/conf.php"
if(!file_exists($conffile)) if(!defined('DONOTLOADCONF') &&file_exists($conffile) &&filesize($conffile) > 8) $conf global MAIN_LOGTOHTML = 1
const MAIN_DB_PREFIX (!isset($dolibarr_main_db_prefix)||! $dolibarr_main_db_prefix) (isset($dolibarr_main_db_prefix) ? $dolibarr_main_db_prefix : '')
const DOL_CLASS_PATH 'class/'
const DOL_DATA_ROOT (isset($dolibarr_main_data_root) ? $dolibarr_main_data_root : '')
const DOL_MAIN_URL_ROOT (isset($dolibarr_main_url_root) ? $dolibarr_main_url_root : '')
$uri = preg_replace('/^http(s?):\/\//i', '', constant('DOL_MAIN_URL_ROOT'))
$suburi = strstr($uri, '/')
const DOL_URL_ROOT ($suburi=='/') $suburi
if(empty($character_set_client)) $conf file character_set_client = strtoupper($character_set_client)
if(empty($dolibarr_main_db_character_set)) $conf db character_set = $dolibarr_main_db_character_set
if(empty($dolibarr_main_db_collation)) $conf db dolibarr_main_db_collation = $dolibarr_main_db_collation
if(empty($dolibarr_main_db_encryption)) $conf db dolibarr_main_db_encryption = $dolibarr_main_db_encryption
if(empty($dolibarr_main_db_cryptkey)) $conf db dolibarr_main_db_cryptkey = $dolibarr_main_db_cryptkey
if(empty($conf->db->user)) $langs = new Translate('..', $conf)
if(GETPOST('lang', 'aZ09')) else
$bc [false] = ' class="bg1"'
$bc [true] = ' class="bg2"'
Detailed Description
File that define environment for support pages.
Definition in file inc.php.
Function Documentation
conf()
conf ($dolibarr_main_document_root)
Load conf file (file must exists)
Parameters
string $dolibarr_main_document_root Root directory of Dolibarr bin files
Returns
int <0 if KO, >0 if OK
Definition at line 190 of file inc.php.
pFooter()
pFooter ($nonext = 0, $setuplang = '')
Print HTML footer.
Parameters
integer $nonext No button "Next step"
string $setuplang Language code
Returns
void
Definition at line 267 of file inc.php.
pHeader()
pHeader ($soutitre, $next, $action = 'none')
Show HTML header.
Parameters
string $soutitre Title
string $next Next
string $action Action code
Returns
void
Definition at line 230 of file inc.php.
Variable Documentation
db
DoliDB db = new stdClass()
API class for accounts.
API class for supplier invoices.
@access protected
Definition at line 41 of file inc.php.
Referenced by GenericObject\__construct(), InterfaceMailmanSpipsynchro\__construct(), TaskStats\__construct(), modMargin\__construct(), modWebServicesClient\__construct(), modWebServices\__construct(), InterfaceActionsBlockedLog\__construct(), InterfaceEventOrganization\__construct(), InterfaceTicketEmail\__construct(), modGravatar\__construct(), modPayBox\__construct(), modDynamicPrices\__construct(), modStripe\__construct(), modNotification\__construct(), InterfaceLdapsynchro\__construct(), InterfaceLogevents\__construct(), modDebugBar\__construct(), modECM\__construct(), modGeoIPMaxmind\__construct(), modLdap\__construct(), modPaypal\__construct(), modSyslog\__construct(), modWorkflow\__construct(), InterfaceWorkflowManager\__construct(), ActionsContactCardDefault\__construct(), modBookmark\__construct(), modClickToDial\__construct(), modExport\__construct(), modFTP\__construct(), modImport\__construct(), modLabel\__construct(), modMailmanSpip\__construct(), InterfaceContactRoles\__construct(), FormAdmin\__construct(), modBarcode\__construct(), modDocumentGeneration\__construct(), modExternalSite\__construct(), modFckeditor\__construct(), ActionsAdherentCardDefault\__construct(), modMailing\__construct(), ActionsCardIndividual\__construct(), InterfaceActionsAuto\__construct(), modDon\__construct(), ActionsCardCompany\__construct(), modOauth\__construct(), Client\__construct(), modPrinting\__construct(), modReceiptPrinter\__construct(), InterfaceStripe\__construct(), CdavLib\__construct(), Utils\__construct(), Fournisseur\__construct(), CoreObject\__construct(), FormContract\__construct(), FormCron\__construct(), TraceableDB\__construct(), FormExpenseReport\__construct(), FormIntervention\__construct(), FormPropal\__construct(), FormSocialContrib\__construct(), FormEcm\__construct(), InterfaceZapierTriggers\__construct(), FormMargin\__construct(), InterfaceMyModuleTriggers\__construct(), FormActions\__construct(), FormBarCode\__construct(), FormWebsite\__construct(), PartnershipUtils\__construct(), PrintingDriver\__construct(), FormBank\__construct(), FormProjets\__construct(), mailing_advthirdparties\__construct(), mailing_xinputfile\__construct(), mailing_xinputuser\__construct(), Interfaces\__construct(), MenuManager\__construct(), MailingTargets\__construct(), FormProduct\__construct(), PriceParser\__construct(), FormAccounting\__construct(), FormFile\__construct(), FormOther\__construct(), mailing_pomme\__construct(), ActionsStripeconnect\__construct(), ExpeditionLineBatch\__construct(), AntiVir\__construct(), mailing_contacts1\__construct(), mailing_example\__construct(), FormResource\__construct(), mailing_fraise\__construct(), InterfaceNotification\__construct(), CommonObjectLine\__construct(), ProductCombination2ValuePair\__construct(), ActionsDatapolicy\__construct(), ExtraLanguages\__construct(), Propalmergepdfproduct\__construct(), RssParser\__construct(), ActionsMyModule\__construct(), Canvas\__construct(), CompanyBankAccount\__construct(), Link\__construct(), Productbatch\__construct(), PriceExpression\__construct(), HookManager\__construct(), Ctypent\__construct(), CommonDocGenerator\__construct(), MailmanSpip\__construct(), CUnits\__construct(), PriceGlobalVariable\__construct(), PaymentTerm\__construct(), Export\__construct(), Dolresource\__construct(), Stripe\__construct(), ProductStockEntrepot\__construct(), UserBankAccount\__construct(), Cstate\__construct(), PaiementFourn\__construct(), Localtax\__construct(), RemiseCheque\__construct(), IntracommReport\__construct(), Ccountry\__construct(), AccountancySystem\__construct(), PriceGlobalVariableUpdater\__construct(), Form\__construct(), FormSms\__construct(), CProductNature\__construct(), ActionsTicket\__construct(), AccountingJournal\__construct(), Productcustomerprice\__construct(), AssetType\__construct(), Tva\__construct(), DolibarrTriggers\__construct(), CActionComm\__construct(), Notify\__construct(), PaymentExpenseReport\__construct(), Comment\__construct(), Bookmark\__construct(), MultiCurrency\__construct(), FichinterRec\__construct(), PaymentVAT\__construct(), Salary\__construct(), PaymentSocialContribution\__construct(), PaymentLoan\__construct(), DiscountAbsolute\__construct(), PaymentDonation\__construct(), LoanSchedule\__construct(), PaymentSalary\__construct(), CommandeFournisseurDispatch\__construct(), Delivery\__construct(), Loan\__construct(), Deplacement\__construct(), Subscription\__construct(), EcmDirectory\__construct(), AdherentType\__construct(), Events\__construct(), ChargeSociales\__construct(), Reception\__construct(), Opensurveysondage\__construct(), AccountancyCategory\__construct(), MouvementStock\__construct(), UserGroup\__construct(), Website\__construct(), Task\__construct(), Productlot\__construct(), Don\__construct(), CashControl\__construct(), Paiement\__construct(), dolReceiptPrinter\__construct(), Establishment\__construct(), Menubase\__construct(), EcmFiles\__construct(), Holiday\__construct(), FormMail\__construct(), PaymentVarious\__construct(), Cronjob\__construct(), BookKeeping\__construct(), Mailing\__construct(), Fichinter\__construct(), ExtraFields\__construct(), ExpenseReport\__construct(), WebsitePage\__construct(), FactureRec\__construct(), Contrat\__construct(), CommandeFournisseur\__construct(), DolibarrModules\__construct(), FactureFournisseur\__construct(), User\__construct(), Adherent\__construct(), Commande\__construct(), ActionComm\__construct(), Facture\__construct(), Product\__construct(), CurrencyRate\__construct(), ProductCombinationLevel\__construct(), RecruitmentCandidatureLine\__construct(), PositionLine\__construct(), KnowledgeRecordLine\__construct(), JobLine\__construct(), DeliveryLine\__construct(), MyObjectLine\__construct(), ConferenceOrBoothAttendeeLine\__construct(), PartnershipLine\__construct(), FichinterLigne\__construct(), AccountLine\__construct(), ExpenseReportLine\__construct(), ExpeditionLigne\__construct(), ContratLigne\__construct(), SupplierProposalLine\__construct(), SupplierInvoiceLine\__construct(), CommandeFournisseurLigne\__construct(), PropaleLigne\__construct(), OrderLine\__construct(), Societe\add_commercial(), TraceableDB\affected_rows(), DoliDBMysqli\affected_rows(), DoliDBSqlite3\affected_rows(), TraceableDB\begin(), CommonInvoice\calculate_date_lim_reglement(), MultiCurrency\checkCodeAlreadyExists(), CommandeFournisseur\classifyBilled(), Commande\classifyBilled(), Commande\classifyUnBilled(), Product\clone_associations(), Product\clone_fournisseurs(), DoliDBMysqli\close(), DoliDBSqlite3\close(), DoliDBPgsql\close(), TraceableDB\close(), DolQueryCollector\collect(), TraceableDB\DDLCreateDb(), TraceableDB\DDLCreateUser(), TraceableDB\DDLGetConnectId(), Fiscalyear\delete(), ChargeSociales\delete(), Loan\delete(), Deplacement\delete(), Establishment\delete(), Link\delete(), ProductStockEntrepot\delete(), CommandeFournisseurDispatch\delete(), Evaluationline\delete(), Productlot\delete(), Website\delete(), EcmFiles\delete(), Cronjob\delete(), BonPrelevement\delete(), FactureLigneRec\delete(), BookKeeping\deleteByImportkey(), FactureFournisseur\deleteline(), TraceableDB\encrypt(), TraceableDB\errno(), DoliDBSqlite3\errno(), DoliDBPgsql\errno(), TraceableDB\error(), DoliDBMysqli\error(), DoliDBPgsql\error(), TraceableDB\escape(), DoliDBMysqli\escape(), TraceableDB\escapeunderscore(), TraceableDB\fetch_array(), TraceableDB\fetch_object(), TraceableDB\fetch_row(), Skill\fetchLines(), TraceableDB\free(), TraceableDB\getDefaultCharacterSetDatabase(), TraceableDB\getDefaultCollationDatabase(), DoliDBMysqli\getDriverInfo(), TraceableDB\getDriverInfo(), ActionsTicket\getInstanceDao(), Skilldet\getLinesArray(), RecruitmentCandidature\getLinesArray(), Evaluationline\getLinesArray(), KnowledgeRecord\getLinesArray(), Position\getLinesArray(), SkillRank\getLinesArray(), Evaluation\getLinesArray(), Job\getLinesArray(), BOM\getLinesArray(), Skill\getLinesArray(), MyObject\getLinesArray(), ConferenceOrBoothAttendee\getLinesArray(), Partnership\getLinesArray(), Mo\getLinesArray(), TraceableDB\getListOfCharacterSet(), TraceableDB\getListOfCollation(), IntracommReport\getNextDeclarationNumber(), TraceableDB\getPathOfDump(), TraceableDB\getPathOfRestore(), DoliDBMysqli\getVersion(), TraceableDB\getVersion(), TraceableDB\getVersionArray(), TraceableDB\ifsql(), TraceableDB\lasterrno(), TraceableDB\lasterror(), TraceableDB\lastquery(), TraceableDB\lastqueryerror(), TraceableDB\num_rows(), DoliDBSqlite3\num_rows(), Tickets\post(), Tickets\postNewMessage(), TraceableDB\query(), DoliDBMysqli\select_db(), TraceableDB\select_db(), Propal\set_availability(), Commande\set_date(), Propal\set_demand_reason(), Propal\set_echeance(), CommandeFournisseur\set_id_projet(), Propal\set_ref_client(), Commande\set_ref_client(), Propal\set_remise_absolue(), Commande\set_remise_absolue(), Facture\set_remise_absolue(), Propal\set_remise_percent(), Commande\set_reopen(), CompanyBankAccount\setAsDefault(), CompanyPaymentMode\setAsDefault(), Inventory\setCanceled(), FactureFournisseur\setCanceled(), Facture\setCanceled(), Propal\setDeliveryDate(), CommandeFournisseur\setDeliveryDate(), Commande\setDeliveryDate(), Commande\setDiscount(), Facture\setDiscount(), Inventory\setDraft(), Propal\setDraft(), Facture\setFinal(), FactureFournisseur\setPaid(), Facture\setPaid(), Inventory\setRecorded(), FactureFournisseur\setUnpaid(), Facture\setUnpaid(), BookKeeping\transformTransaction(), Subscription\update(), ChargeSociales\update(), AccountingAccount\update(), Loan\update(), AccountLine\update(), User\update_clicktodial(), Adherent\update_end_date(), ContratLigne\update_total(), SupplierProposalLine\update_total(), SupplierInvoiceLine\update_total(), PropaleLigne\update_total(), OrderLine\update_total(), FactureLigne\update_total(), Holiday\updateBalance(), CommandeFournisseur\updateFromCommandeClient(), and ActionComm\updatePercent().
else
if (GETPOST('lang', 'aZ09')) else
Initial value:
{
    $langs->setDefaultLang('auto')
Definition at line 176 of file inc.php.