var group__takepos =
[
    [ "cashcontrol_card.php", "d1/d77/cashcontrol__card_8php.html", null ],
    [ "cashcontrol_list.php", "dc/da5/cashcontrol__list_8php.html", null ],
    [ "cashcontrol.class.php", "d5/d65/cashcontrol_8class_8php.html", null ],
    [ "report.php", "d8/dda/report_8php.html", null ],
    [ "modTakePos.class.php", "d3/def/mod_take_pos_8class_8php.html", null ],
    [ "mod_takepos_ref_simple.php", "d6/d42/mod__takepos__ref__simple_8php.html", null ],
    [ "mod_takepos_ref_universal.php", "da/d56/mod__takepos__ref__universal_8php.html", null ],
    [ "modules_takepos.php", "dd/d1d/modules__takepos_8php.html", null ],
    [ "appearance.php", "da/de5/appearance_8php.html", null ],
    [ "bar.php", "dd/de2/bar_8php.html", null ],
    [ "orderprinters.php", "d9/d01/orderprinters_8php.html", null ],
    [ "setup.php", "dd/d3a/takepos_2admin_2setup_8php.html", null ],
    [ "printqr.php", "d8/de0/printqr_8php.html", null ],
    [ "terminal.php", "d2/d3b/terminal_8php.html", null ],
    [ "setup.php", "dd/d3a/takepos_2admin_2setup_8php.html", null ],
    [ "terminal.php", "d2/d3b/terminal_8php.html", null ],
    [ "floors.php", "de/d0e/floors_8php.html", null ],
    [ "freezone.php", "db/d88/freezone_8php.html", null ],
    [ "index.php", "d1/dfd/takepos_2index_8php.html", null ],
    [ "invoice.php", "d2/d4d/invoice_8php.html", null ],
    [ "pay.php", "d3/da2/pay_8php.html", null ],
    [ "phone.php", "dc/d29/phone_8php.html", null ],
    [ "printbox.php", "d2/d9f/printbox_8php.html", null ],
    [ "auto_order.php", "dc/d2e/auto__order_8php.html", null ],
    [ "menu.php", "df/daa/menu_8php.html", null ],
    [ "receipt.php", "d3/da1/receipt_8php.html", null ],
    [ "reduction.php", "d3/da9/reduction_8php.html", null ],
    [ "send.php", "d8/d64/send_8php.html", null ],
    [ "smpcb.php", "de/d43/smpcb_8php.html", null ],
    [ "split.php", "d9/dd3/split_8php.html", null ]
];