var modules =
[
    [ "Module DolibarrApi", "d0/d2d/group__api.html", "d0/d2d/group__api" ],
    [ "Module foundation", "d0/d72/group__member.html", "d0/d72/group__member" ],
    [ "Module agenda", "d1/d40/group__agenda.html", "d1/d40/group__agenda" ],
    [ "Module Assets", "d7/dd0/group__asset.html", "d7/dd0/group__asset" ],
    [ "Module bank", "d4/d78/group__banque.html", "d4/d78/group__banque" ],
    [ "Module barcode", "d2/dea/group__barcode.html", "d2/dea/group__barcode" ],
    [ "Module BlockedLog", "d2/da7/group__blockedlog.html", "d2/da7/group__blockedlog" ],
    [ "Module Bom", "de/df9/group__bom.html", "de/df9/group__bom" ],
    [ "Module bookmarks", "dc/d90/group__bookmark.html", "dc/d90/group__bookmark" ],
    [ "Module points of sale", "dd/d75/group__pos.html", "dd/d75/group__pos" ],
    [ "Module categories", "d8/d3f/group__category.html", "d8/d3f/group__category" ],
    [ "Module clicktodial", "db/de9/group__clicktodial.html", "db/de9/group__clicktodial" ],
    [ "Module collab", "d7/d91/group__collab.html", "d7/d91/group__collab" ],
    [ "Module orders", "d5/dd7/group__commande.html", "d5/dd7/group__commande" ],
    [ "Module comptabilite", "d7/d5b/group__comptabilite.html", "d7/d5b/group__comptabilite" ],
    [ "Module contract", "d5/dc8/group__contrat.html", "d5/dc8/group__contrat" ],
    [ "Module cron", "d3/dbf/group__cron.html", "d3/dbf/group__cron" ],
    [ "Module datapolicy", "d5/d2d/group__datapolicy.html", "d5/d2d/group__datapolicy" ],
    [ "Module dav", "d6/d94/group__dav.html", "d6/d94/group__dav" ],
    [ "Module Debug bar", "d7/d1f/group__debugbar.html", "d7/d1f/group__debugbar" ],
    [ "Module trips", "d2/d6f/group__deplacement.html", "d2/d6f/group__deplacement" ],
    [ "Module mass mailings", "d3/d73/group__document.html", "d3/d73/group__document" ],
    [ "Module donations", "da/d08/group__don.html", "da/d08/group__don" ],
    [ "Module dynamic prices", "da/dd4/group__produit.html", "da/dd4/group__produit" ],
    [ "Module ecm", "dd/dea/group__ecm.html", "dd/dea/group__ecm" ],
    [ "Module emailcollector", "df/db0/group__emailcollector.html", "df/db0/group__emailcollector" ],
    [ "Module shipping", "d0/d73/group__expedition.html", "d0/d73/group__expedition" ],
    [ "Module expensereport", "d2/d2e/group__expensereport.html", "d2/d2e/group__expensereport" ],
    [ "Module export", "d2/d57/group__export.html", "d2/d57/group__export" ],
    [ "Module externalrss", "d5/d02/group__externalrss.html", "d5/d02/group__externalrss" ],
    [ "Module externalsite", "d5/d19/group__externalsite.html", "d5/d19/group__externalsite" ],
    [ "Module invoices", "d8/d40/group__facture.html", "d8/d40/group__facture" ],
    [ "Module fckeditor", "de/dbe/group__fckeditor.html", "de/dbe/group__fckeditor" ],
    [ "Module Interventions", "d1/d8e/group__ficheinter.html", "d1/d8e/group__ficheinter" ],
    [ "Module suppliers", "d9/dce/group__fournisseur.html", "d9/dce/group__fournisseur" ],
    [ "Module ftp", "da/ddd/group__ftp.html", "da/ddd/group__ftp" ],
    [ "Module geoipmaxmind", "de/dfe/group__geoip.html", "de/dfe/group__geoip" ],
    [ "Module gravatar", "d0/de8/group__gravatar.html", "d0/de8/group__gravatar" ],
    [ "Module holiday", "d6/d39/group__holiday.html", "d6/d39/group__holiday" ],
    [ "Module import", "d6/dfd/group__import.html", "d6/dfd/group__import" ],
    [ "Module MyModule", "d5/db9/group__incoterm.html", "d5/db9/group__incoterm" ],
    [ "Module labels", "d4/d49/group__label.html", null ],
    [ "Module ldap", "db/d28/group__ldap.html", "db/d28/group__ldap" ],
    [ "Module Loans", "d2/d21/group__tax.html", "d2/d21/group__tax" ],
    [ "Module emailing", "d1/d52/group__mailing.html", "d1/d52/group__mailing" ],
    [ "Module mailmanspip", "db/d95/group__mailmanspip.html", "db/d95/group__mailmanspip" ],
    [ "Module margin", "d9/d3d/group__margin.html", "d9/d3d/group__margin" ],
    [ "Module ModuleBuilder", "d2/db4/group__modulebuilder.html", "d2/db4/group__modulebuilder" ],
    [ "Module Mrp", "d3/df3/group__mrp.html", "d3/df3/group__mrp" ],
    [ "Module MultiCurrency", "d7/dd0/group__multicurrency.html", "d7/dd0/group__multicurrency" ],
    [ "Module email notification", "da/d4f/group__notification.html", "da/d4f/group__notification" ],
    [ "Module oauth", "dd/d1f/group__oauth.html", "dd/d1f/group__oauth" ],
    [ "Module opensurvey", "d8/d1b/group__opensurvey.html", "d8/d1b/group__opensurvey" ],
    [ "Module paybox", "d2/da9/group__paybox.html", "d2/da9/group__paybox" ],
    [ "Module paymentbybanktransfer", "dd/dcd/group__paymentbybanktransfer.html", "dd/dcd/group__paymentbybanktransfer" ],
    [ "Module paypal", "d6/da3/group__paypal.html", "d6/da3/group__paypal" ],
    [ "Module prelevement", "d3/d86/group__prelevement.html", "d3/d86/group__prelevement" ],
    [ "Module printing", "d8/d7c/group__printing.html", "d8/d7c/group__printing" ],
    [ "Module batch number management", "d5/d04/group__productbatch.html", "d5/d04/group__productbatch" ],
    [ "Module project", "de/d85/group__projet.html", "de/d85/group__projet" ],
    [ "Module commercial proposals", "dd/d70/group__propale.html", "dd/d70/group__propale" ],
    [ "Module reception", "d6/d99/group__reception.html", "d6/d99/group__reception" ],
    [ "Module Recruitment", "d5/d4a/group__recruitment.html", "d5/d4a/group__recruitment" ],
    [ "Module resource", "db/db6/group__resource.html", "db/db6/group__resource" ],
    [ "Module salaries", "dc/dc3/group__salaries.html", "dc/dc3/group__salaries" ],
    [ "Module services", "d7/d27/group__service.html", "d7/d27/group__service" ],
    [ "Module SocialNetworks", "d4/d69/group___social_networks.html", null ],
    [ "Module societe", "d2/d5c/group__societe.html", "d2/d5c/group__societe" ],
    [ "Module stocks", "db/db4/group__stock.html", "db/db4/group__stock" ],
    [ "Module stripe", "d4/de0/group__stripe.html", "d4/de0/group__stripe" ],
    [ "Module supplier_proposal", "d0/db7/group__supplier__proposal.html", "d0/db7/group__supplier__proposal" ],
    [ "Module syslog", "d3/d39/group__syslog.html", "d3/d39/group__syslog" ],
    [ "Module TakePos", "d4/df2/group__takepos.html", "d4/df2/group__takepos" ],
    [ "Module Ticket", "d5/db8/group__ticket.html", "d5/db8/group__ticket" ],
    [ "Module user management", "d9/d85/group__user.html", "d9/d85/group__user" ],
    [ "Module webservices", "d1/d75/group__webservices.html", "d1/d75/group__webservices" ],
    [ "Module website", "da/dfd/group__website.html", "da/dfd/group__website" ],
    [ "Module workflow", "dc/d92/group__workflow.html", "dc/d92/group__workflow" ],
    [ "Module Zapier", "d3/d47/group__zapier.html", "d3/d47/group__zapier" ],
    [ "Module MyModule", "d8/d33/group__mymodule.html", "d8/d33/group__mymodule" ]
];