Dolibarr: Ldap Class Reference
Ldap Class Reference
Class to manage LDAP features.
Public Member Functions
__construct ()
Constructor.
connect_bind ()
Connect and bind Use this->server, this->serverPort, this->ldapProtocolVersion, this->serverType, this->searchUser, this->searchPassword After return, this->connection and $this->bind are defined.
close ()
Simply closes the connection set up earlier.
bind ()
Anonymously binds to the connection.
bindauth ($bindDn, $pass)
Binds as an authenticated user, which usually allows for write access.
unbind ()
Unbind du serveur ldap.
getVersion ()
Verification de la version du serveur ldap.
setVersion ()
Change ldap protocol version to use.
setReferrals ()
changement du referrals.
add ($dn, $info, $user)
Add a LDAP entry Ldap object connect and bind must have been done.
modify ($dn, $info, $user)
Modify a LDAP entry Ldap object connect and bind must have been done.
rename ($dn, $newrdn, $newparent, $user, $deleteoldrdn=true)
Rename a LDAP entry Ldap object connect and bind must have been done.
update ($dn, $info, $user, $olddn, $newrdn=false, $newparent=false)
Modify a LDAP entry (to use if dn != olddn) Ldap object connect and bind must have been done.
delete ($dn)
Delete a LDAP entry Ldap object connect and bind must have been done.
dump_content ($dn, $info)
Build a LDAP message.
dump ($dn, $info)
Dump a LDAP message to ldapinput.in file.
serverPing ($host, $port=389, $timeout=1)
Ping a server before ldap_connect for avoid waiting.
addAttribute ($dn, $info, $user)
Add a LDAP attribute in entry Ldap object connect and bind must have been done.
updateAttribute ($dn, $info, $user)
Update a LDAP attribute in entry Ldap object connect and bind must have been done.
deleteAttribute ($dn, $info, $user)
Delete a LDAP attribute in entry Ldap object connect and bind must have been done.
getAttribute ($dn, $filter)
Returns an array containing attributes and values for first record.
getAttributeValues ($filterrecord, $attribute)
Returns an array containing values for an attribute and for first record matching filterrecord.
getRecords ($search, $userDn, $useridentifier, $attributeArray, $activefilter=0, $attributeAsArray=array())
Returns an array containing a details or list of LDAP record(s) ldapsearch -LLLx -hlocalhost -Dcn=admin,dc=parinux,dc=org -w password -b "ou=adherents,ou=people,dc=parinux,dc=org" userPassword.
littleEndian ($hex)
Converts a little-endian hex-number to one, that 'hexdec' can convert Required by Active Directory.
getObjectSid ($ldapUser)
Recupere le SID de l'utilisateur Required by Active Directory.
binSIDtoText ($binsid)
Returns the textual SID Indispensable pour Active Directory.
search ($checkDn, $filter)
Fonction de recherche avec filtre this->connection doit etre defini donc la methode bind ou bindauth doit avoir deja ete appelee Ne pas utiliser pour recherche d'une liste donnee de proprietes car conflit majuscule-minuscule.
fetch ($user, $filter)
Load all attribute of a LDAP user.
getUserIdentifier ()
Returns the correct user identifier to use, based on the ldap server type.
parseUACF ($uacf)
UserAccountControl Flgs to more human understandable form...
parseSAT ($samtype)
SamAccountType value to text.
convert_time ($value)
Convertit le temps ActiveDirectory en Unix timestamp.
convFromOutputCharset ($str, $pagecodeto='UTF-8')
Convert a string from output/memory charset.
getNextGroupGid ($keygroup='LDAP_KEY_GROUPS')
Return available value of group GID.
Public Attributes
$error = ''
$errors = array()
$server = array()
Tableau des serveurs (IP addresses ou nom d'hotes)
$dn
Base DN (e.g.
$serverType
type de serveur, actuellement OpenLdap et Active Directory
$ldapProtocolVersion
Version du protocole ldap.
$domain
Server DN.
$searchUser
User administrateur Ldap Active Directory ne supporte pas les connexions anonymes.
$searchPassword
Mot de passe de l'administrateur Active Directory ne supporte pas les connexions anonymes.
$people
DN des utilisateurs.
$groups
DN des groupes.
$ldapErrorCode
Code erreur retourne par le serveur Ldap.
$ldapErrorText
Message texte de l'erreur.
$name
$firstname
$login
$phone
$skype
$fax
$mail
$mobile
$uacf
$pwdlastset
$ldapcharset = 'UTF-8'
$connection
The internal LDAP connection handle.
$result
Result of any connections etc.
Private Member Functions
convToOutputCharset ($str, $pagecodefrom='UTF-8')
Convert a string into output/memory charset.
Detailed Description
Class to manage LDAP features.
Definition at line 30 of file ldap.class.php.
Member Function Documentation
add()
add ($dn, $info, $user)
Add a LDAP entry Ldap object connect and bind must have been done.
Parameters
string $dn DN entry key
array $info Attributes array
User $user Objet user that create
Returns
int <0 if KO, >0 if OK
Definition at line 417 of file ldap.class.php.
addAttribute()
addAttribute ($dn, $info, $user)
Add a LDAP attribute in entry Ldap object connect and bind must have been done.
Parameters
string $dn DN entry key
array $info Attributes array
User $user Objet user that create
Returns
int <0 if KO, >0 if OK
Definition at line 774 of file ldap.class.php.
bind()
bind ()
Anonymously binds to the connection.
After this is done, queries and searches can be done - but read-only.
Returns
boolean true or false
Definition at line 315 of file ldap.class.php.
bindauth()
bindauth ($bindDn, $pass)
Binds as an authenticated user, which usually allows for write access.
The FULL dn must be passed. For a directory manager, this is "cn=Directory Manager" under iPlanet. For a user, it will be something like "uid=jbloggs,ou=People,dc=foo,dc=com".
Parameters
string $bindDn DN
string $pass Password
Returns
boolean true or false
Definition at line 340 of file ldap.class.php.
Referenced by getObjectSid().
binSIDtoText()
binSIDtoText ($binsid)
Returns the textual SID Indispensable pour Active Directory.
Parameters
string $binsid Binary SID
Returns
string Textual SID
Definition at line 1201 of file ldap.class.php.
close()
close ()
Simply closes the connection set up earlier.
Returns true if OK, false if there was an error.
Returns
boolean true or false
Definition at line 297 of file ldap.class.php.
connect_bind()
connect_bind ()
Connect and bind Use this->server, this->serverPort, this->ldapProtocolVersion, this->serverType, this->searchUser, this->searchPassword After return, this->connection and $this->bind are defined.
Returns
int <0 if KO, 1 if bind anonymous, 2 if bind auth
Definition at line 164 of file ldap.class.php.
convert_time()
convert_time ($value)
Convertit le temps ActiveDirectory en Unix timestamp.
Parameters
string $value AD time to convert
Returns
integer Unix timestamp
Definition at line 1449 of file ldap.class.php.
convFromOutputCharset()
convFromOutputCharset ($str, $pagecodeto = 'UTF-8')
Convert a string from output/memory charset.
Parameters
string $str String to convert
string $pagecodeto Page code for result string
Returns
string Converted string
Definition at line 1482 of file ldap.class.php.
convToOutputCharset()
convToOutputCharset ($str, $pagecodefrom = 'UTF-8') private
Convert a string into output/memory charset.
Parameters
string $str String to convert
string $pagecodefrom Page code of src string
Returns
string Converted string
Definition at line 1467 of file ldap.class.php.
delete()
delete ($dn)
Delete a LDAP entry Ldap object connect and bind must have been done.
Parameters
string $dn DN entry key
Returns
int <0 if KO, >0 if OK
Definition at line 634 of file ldap.class.php.
References $dn, and dol_syslog().
deleteAttribute()
deleteAttribute ($dn, $info, $user)
Delete a LDAP attribute in entry Ldap object connect and bind must have been done.
Parameters
string $dn DN entry key
array $info Attributes array
User $user Objet user that create
Returns
int <0 if KO, >0 if OK
Definition at line 878 of file ldap.class.php.
dump()
dump ($dn, $info)
Dump a LDAP message to ldapinput.in file.
Parameters
string $dn DN entry key
array $info Attributes array
Returns
int <0 if KO, >0 if OK
Definition at line 710 of file ldap.class.php.
dump_content()
dump_content ($dn, $info)
Build a LDAP message.
Parameters
string $dn DN entry key
array $info Attributes array
Returns
string Content of file
Definition at line 667 of file ldap.class.php.
fetch()
fetch ($user, $filter)
Load all attribute of a LDAP user.
Parameters
User $user User to search for. Not used if a filter is provided.
string $filter Filter for search. Must start with &. Examples: &(objectClass=inetOrgPerson) &(objectClass=user)(objectCategory=person) &(isMemberOf=cn=Sales,ou=Groups,dc=opencsi,dc=com)
Returns
int >0 if OK, <0 if KO
Definition at line 1263 of file ldap.class.php.
getAttribute()
getAttribute ($dn, $filter)
Returns an array containing attributes and values for first record.
Parameters
string $dn DN entry key
string $filter Filter
Returns
int|array <0 or false if KO, array if OK
Definition at line 928 of file ldap.class.php.
getAttributeValues()
getAttributeValues ($filterrecord, $attribute)
Returns an array containing values for an attribute and for first record matching filterrecord.
Parameters
string $filterrecord Record
string $attribute Attributes
Returns
void
Definition at line 973 of file ldap.class.php.
getNextGroupGid()
getNextGroupGid ($keygroup = 'LDAP_KEY_GROUPS')
Return available value of group GID.
Parameters
string $keygroup Key of group
Returns
int gid number
Definition at line 1497 of file ldap.class.php.
getObjectSid()
getObjectSid ($ldapUser)
Recupere le SID de l'utilisateur Required by Active Directory.
Parameters
string $ldapUser Login de l'utilisateur
Returns
string Sid
Definition at line 1142 of file ldap.class.php.
References bindauth().
getRecords()
getRecords ($search, $userDn, $useridentifier, $attributeArray, $activefilter = 0, $attributeAsArray = array())
Returns an array containing a details or list of LDAP record(s) ldapsearch -LLLx -hlocalhost -Dcn=admin,dc=parinux,dc=org -w password -b "ou=adherents,ou=people,dc=parinux,dc=org" userPassword.
Parameters
string $search Value of fiel to search, '*' for all. Not used if $activefilter is set.
string $userDn DN (Ex: ou=adherents,ou=people,dc=parinux,dc=org)
string $useridentifier Name of key field (Ex: uid)
array $attributeArray Array of fields required. Note this array must also contains field $useridentifier (Ex: sn,userPassword)
int $activefilter '1' or 'user'=use field this->filter as filter instead of parameter $search, 'member'=use field this->filtermember as filter
array $attributeAsArray Array of fields wanted as an array not a string
Returns
array Array of [id_record][ldap_field]=value
Definition at line 1018 of file ldap.class.php.
getUserIdentifier()
getUserIdentifier ()
Returns the correct user identifier to use, based on the ldap server type.
Returns
string Login
Definition at line 1356 of file ldap.class.php.
getVersion()
getVersion ()
Verification de la version du serveur ldap.
Returns
string version
Definition at line 376 of file ldap.class.php.
littleEndian()
littleEndian ($hex)
Converts a little-endian hex-number to one, that 'hexdec' can convert Required by Active Directory.
Parameters
string $hex Hex value
Returns
string Little endian
Definition at line 1126 of file ldap.class.php.
References $result, and dol_strlen().
modify()
modify ($dn, $info, $user)
Modify a LDAP entry Ldap object connect and bind must have been done.
Parameters
string $dn DN entry key
array $info Attributes array
User $user Objet user that modify
Returns
int <0 if KO, >0 if OK
Definition at line 471 of file ldap.class.php.
parseSAT()
parseSAT ($samtype)
SamAccountType value to text.
Parameters
string $samtype SamType
Returns
string Sam string
Definition at line 1418 of file ldap.class.php.
parseUACF()
parseUACF ($uacf)
UserAccountControl Flgs to more human understandable form...
Parameters
string $uacf UACF
Returns
void
Definition at line 1371 of file ldap.class.php.
rename()
rename ($dn, $newrdn, $newparent, $user, $deleteoldrdn = true)
Rename a LDAP entry Ldap object connect and bind must have been done.
Parameters
string $dn Old DN entry key (uid=qqq,ou=xxx,dc=aaa,dc=bbb) (before update)
string $newrdn New RDN entry key (uid=qqq)
string $newparent New parent (ou=xxx,dc=aaa,dc=bbb)
User $user Objet user that modify
bool $deleteoldrdn If true the old RDN value(s) is removed, else the old RDN value(s) is retained as non-distinguished values of the entry.
Returns
int <0 if KO, >0 if OK
Definition at line 527 of file ldap.class.php.
search()
search ($checkDn, $filter)
Fonction de recherche avec filtre this->connection doit etre defini donc la methode bind ou bindauth doit avoir deja ete appelee Ne pas utiliser pour recherche d'une liste donnee de proprietes car conflit majuscule-minuscule.
A n'utiliser que pour les pages 'Fiche LDAP' qui affiche champ lisibles par defaut.
Parameters
string $checkDn DN de recherche (Ex: ou=users,cn=my-domain,cn=com)
string $filter Search filter (ex: (sn=nom_personne))
Returns
array|int Array with answers (key lowercased - value)
Definition at line 1227 of file ldap.class.php.
serverPing()
serverPing ($host, $port = 389, $timeout = 1)
Ping a server before ldap_connect for avoid waiting.
Parameters
string $host Server host or address
int $port Server port (default 389)
int $timeout Timeout in second (default 1s)
Returns
boolean true or false
Definition at line 744 of file ldap.class.php.
setReferrals()
setReferrals ()
changement du referrals.
Returns
boolean referrals
Definition at line 400 of file ldap.class.php.
setVersion()
setVersion ()
Change ldap protocol version to use.
Returns
boolean version
Definition at line 388 of file ldap.class.php.
unbind()
unbind ()
Unbind du serveur ldap.
Returns
boolean true or false
Definition at line 360 of file ldap.class.php.
update()
update ($dn, $info, $user, $olddn, $newrdn = false, $newparent = false)
Modify a LDAP entry (to use if dn != olddn) Ldap object connect and bind must have been done.
Parameters
string $dn DN entry key
array $info Attributes array
User $user Objet user that update
string $olddn Old DN entry key (before update)
string $newrdn New RDN entry key (uid=qqq) (for ldap_rename)
string $newparent New parent (ou=xxx,dc=aaa,dc=bbb) (for ldap_rename)
Returns
int <0 if KO, >0 if OK
Definition at line 576 of file ldap.class.php.
updateAttribute()
updateAttribute ($dn, $info, $user)
Update a LDAP attribute in entry Ldap object connect and bind must have been done.
Parameters
string $dn DN entry key
array $info Attributes array
User $user Objet user that create
Returns
int <0 if KO, >0 if OK
Definition at line 826 of file ldap.class.php.
Member Data Documentation
$dn
$dn
Base DN (e.g.
"dc=foo,dc=com")
Definition at line 50 of file ldap.class.php.
Referenced by delete().
The documentation for this class was generated from the following file:
htdocs/core/class/ldap.class.php