Dolibarr: Products Class Reference
Products Class Reference
Public Member Functions
__construct ()
Constructor.
get ($id, $includestockdata=0, $includesubproducts=false, $includeparentid=false, $includetrans=false)
Get properties of a product object by id.
getByRef ($ref, $includestockdata=0, $includesubproducts=false, $includeparentid=false, $includetrans=false)
Get properties of a product object by ref.
getByRefExt ($ref_ext, $includestockdata=0, $includesubproducts=false, $includeparentid=false, $includetrans=false)
Get properties of a product object by ref_ext.
getByBarcode ($barcode, $includestockdata=0, $includesubproducts=false, $includeparentid=false, $includetrans=false)
Get properties of a product object by barcode.
index ($sortfield="t.ref", $sortorder='ASC', $limit=100, $page=0, $mode=0, $category=0, $sqlfilters='', $ids_only=false, $variant_filter=0, $pagination_data=false)
List products.
post ($request_data=null)
Create product object.
put ($id, $request_data=null)
Update product.
delete ($id)
Delete product.
getSubproducts ($id)
Get the list of subproducts of the product.
addSubproducts ($id, $subproduct_id, $qty, $incdec=1)
Add subproduct.
delSubproducts ($id, $subproduct_id)
Remove subproduct.
getCategories ($id, $sortfield="s.rowid", $sortorder='ASC', $limit=0, $page=0)
Get categories for a product.
getCustomerPricesPerSegment ($id)
Get prices per segment for a product.
getCustomerPricesPerCustomer ($id, $thirdparty_id='')
Get prices per customer for a product.
getCustomerPricesPerQuantity ($id)
Get prices per quantity for a product.
addPurchasePrice ($id, $qty, $buyprice, $price_base_type, $fourn_id, $availability, $ref_fourn, $tva_tx, $charges=0, $remise_percent=0, $remise=0, $newnpr=0, $delivery_time_days=0, $supplier_reputation='', $localtaxes_array=array(), $newdefaultvatcode='', $multicurrency_buyprice=0, $multicurrency_price_base_type='HT', $multicurrency_tx=1, $multicurrency_code='', $desc_fourn='', $barcode='', $fk_barcode_type=null)
Add/Update purchase prices for a product.
deletePurchasePrice ($id, $priceid)
Delete purchase price for a product.
getSupplierProducts ($sortfield="t.ref", $sortorder='ASC', $limit=100, $page=0, $mode=0, $category=0, $supplier=0, $sqlfilters='')
Get a list of all purchase prices of products.
getPurchasePrices ($id, $ref='', $ref_ext='', $barcode='')
Get purchase prices for a product.
getAttributes ($sortfield="t.ref", $sortorder='ASC', $limit=100, $page=0, $sqlfilters='')
Get attributes.
getAttributeById ($id)
Get attribute by ID.
getAttributesByRef ($ref)
Get attributes by ref.
getAttributesByRefExt ($ref_ext)
Get attributes by ref_ext.
addAttributes ($ref, $label, $ref_ext='')
Add attributes.
putAttributes ($id, $request_data=null)
Update attributes by id.
deleteAttributes ($id)
Delete attributes by id.
getAttributeValueById ($id)
Get attribute value by id.
getAttributeValueByRef ($id, $ref)
Get attribute value by ref.
deleteAttributeValueByRef ($id, $ref)
Delete attribute value by ref.
getAttributeValues ($id)
Get all values for an attribute id.
getAttributeValuesByRef ($ref)
Get all values for an attribute ref.
addAttributeValue ($id, $ref, $value)
Add attribute value.
putAttributeValue ($id, $request_data)
Update attribute value.
deleteAttributeValueById ($id)
Delete attribute value by id.
getVariants ($id, $includestock=0)
Get product variants.
getVariantsByProdRef ($ref)
Get product variants by Product ref.
addVariant ($id, $weight_impact, $price_impact, $price_impact_is_percent, $features, $reference='', $ref_ext='')
Add variant.
addVariantByProductRef ($ref, $weight_impact, $price_impact, $price_impact_is_percent, $features)
Add variant by product ref.
putVariant ($id, $request_data=null)
Put product variants.
deleteVariant ($id)
Delete product variants.
getStock ($id, $selected_warehouse_id=null)
Get stock data for the product id given.
Public Member Functions inherited from DolibarrApi
__construct ($db, $cachedir='', $refreshCache=false)
Constructor.
Public Attributes
$product
$productsupplier
Public Attributes inherited from DolibarrApi
$r
Static Public Attributes
static $FIELDS
Protected Member Functions
_cleanObjectDatas ($object)
Clean sensible object datas.
Protected Member Functions inherited from DolibarrApi
_checkValForAPI ($field, $value, $object)
Check and convert a string depending on its type/name.
_checkFilters ($sqlfilters)
Return if a $sqlfilters parameter is valid.
Private Member Functions
_validate ($data)
Validate fields before create or update object.
_fetch ($id, $ref='', $ref_ext='', $barcode='', $includestockdata=0, $includesubproducts=false, $includeparentid=false, $includeifobjectisused=false, $includetrans=false)
Get properties of 1 product object.
Additional Inherited Members
Static Protected Member Functions inherited from DolibarrApi
static _checkAccessToResource ($resource, $resource_id=0, $dbtablename='', $feature2='', $dbt_keyfield='fk_soc', $dbt_select='rowid')
Check access by user to a given resource.
static _forge_criteria_callback ($matches)
Function to forge a SQL criteria.
Protected Attributes inherited from DolibarrApi
$db
Detailed Description
Definition at line 35 of file api_products.class.php.
Member Function Documentation
_cleanObjectDatas()
_cleanObjectDatas ($object) protected
Clean sensible object datas.
Parameters
Object $object Object to clean
Returns
Object Object with cleaned properties
Reimplemented from DolibarrApi.
Definition at line 1897 of file api_products.class.php.
_fetch()
_fetch ($id, $ref = '', $ref_ext = '', $barcode = '', $includestockdata = 0, $includesubproducts = false, $includeparentid = false, $includeifobjectisused = false, $includetrans = false) private
Get properties of 1 product object.
Return an array with product information.
Parameters
int $id ID of product
string $ref Ref of element
string $ref_ext Ref ext of element
string $barcode Barcode of element
int $includestockdata Load also information about stock (slower)
bool $includesubproducts Load information about subproducts (if product is a virtual product)
bool $includeparentid Load also ID of parent product (if product is a variant of a parent product)
bool $includeifobjectisused Check if product object is used and set property 'is_object_used' with result.
bool $includetrans Load also the translations of product label and description
Returns
array|mixed Data without useless information
Exceptions
RestException 401
RestException 403
RestException 404
Definition at line 1990 of file api_products.class.php.
Referenced by getByBarcode(), and getByRefExt().
_validate()
_validate ($data) private
Validate fields before create or update object.
Parameters
array $data Datas to validate
Returns
array
Exceptions
RestException
Definition at line 1959 of file api_products.class.php.
addAttributes()
addAttributes ($ref, $label, $ref_ext = '')
Add attributes.
Parameters
string $ref Reference of Attribute
string $label Label of Attribute
string $ref_ext Reference of Attribute
Returns
int
Exceptions
RestException 500
RestException 401
@url POST attributes
Definition at line 1195 of file api_products.class.php.
addAttributeValue()
addAttributeValue ($id, $ref, $value)
Add attribute value.
Parameters
int $id ID of Attribute
string $ref Reference of Attribute value
string $value Value of Attribute value
Returns
int
Exceptions
RestException 500
RestException 401
@url POST attributes/{id}/values
Definition at line 1500 of file api_products.class.php.
addPurchasePrice()
addPurchasePrice ($id, $qty, $buyprice, $price_base_type, $fourn_id, $availability, $ref_fourn, $tva_tx, $charges = 0, $remise_percent = 0, $remise = 0, $newnpr = 0, $delivery_time_days = 0, $supplier_reputation = '', $localtaxes_array = array(), $newdefaultvatcode = '', $multicurrency_buyprice = 0, $multicurrency_price_base_type = 'HT', $multicurrency_tx = 1, $multicurrency_code = '', $desc_fourn = '', $barcode = '', $fk_barcode_type = null)
Add/Update purchase prices for a product.
Parameters
int $id ID of Product
float $qty Min quantity for which price is valid
float $buyprice Purchase price for the quantity min
string $price_base_type HT or TTC
int $fourn_id Supplier ID
int $availability Product availability
string $ref_fourn Supplier ref
float $tva_tx New VAT Rate (For example 8.5. Should not be a string)
string $charges costs affering to product
float $remise_percent Discount regarding qty (percent)
float $remise Discount regarding qty (amount)
int $newnpr Set NPR or not
int $delivery_time_days Delay in days for delivery (max). May be '' if not defined.
string $supplier_reputation Reputation with this product to the defined supplier (empty, FAVORITE, DONOTORDER)
array $localtaxes_array Array with localtaxes info array('0'=>type1,'1'=>rate1,'2'=>type2,'3'=>rate2) (loaded by getLocalTaxesFromRate(vatrate, 0, ...) function).
string $newdefaultvatcode Default vat code
float $multicurrency_buyprice Purchase price for the quantity min in currency
string $multicurrency_price_base_type HT or TTC in currency
float $multicurrency_tx Rate currency
string $multicurrency_code Currency code
string $desc_fourn Custom description for product_fourn_price
string $barcode Barcode
int $fk_barcode_type Barcode type
Returns
int
Exceptions
RestException 500
RestException 401
@url POST {id}/purchase_prices
Definition at line 733 of file api_products.class.php.
addSubproducts()
addSubproducts ($id, $subproduct_id, $qty, $incdec = 1)
Add subproduct.
Link a product/service to a parent product/service
Parameters
int $id Id of parent product/service
int $subproduct_id Id of child product/service
int $qty Quantity
int $incdec 1=Increase/decrease stock of child when parent stock increase/decrease
Returns
int
Exceptions
RestException
RestException 401
RestException 404
@url POST {id}/subproducts/add
Definition at line 491 of file api_products.class.php.
addVariant()
addVariant ($id, $weight_impact, $price_impact, $price_impact_is_percent, $features, $reference = '', $ref_ext = '')
Add variant.
"features" is a list of attributes pairs id_attribute=>id_value. Example: array(id_color=>id_Blue, id_size=>id_small, id_option=>id_val_a, ...)
Parameters
int $id ID of Product
float $weight_impact Weight impact of variant
float $price_impact Price impact of variant
bool $price_impact_is_percent Price impact in percent (true or false)
array $features List of attributes pairs id_attribute->id_value. Example: array(id_color=>id_Blue, id_size=>id_small, id_option=>id_val_a, ...)
string $reference Customized reference of variant
string $ref_ext External reference of variant
Returns
int
Exceptions
RestException 500
RestException 401
RestException 404
@url POST {id}/variants
Definition at line 1685 of file api_products.class.php.
addVariantByProductRef()
addVariantByProductRef ($ref, $weight_impact, $price_impact, $price_impact_is_percent, $features)
Add variant by product ref.
"features" is a list of attributes pairs id_attribute=>id_value. Example: array(id_color=>id_Blue, id_size=>id_small, id_option=>id_val_a, ...)
Parameters
string $ref Ref of Product
float $weight_impact Weight impact of variant
float $price_impact Price impact of variant
bool $price_impact_is_percent Price impact in percent (true or false)
array $features List of attributes pairs id_attribute->id_value. Example: array(id_color=>id_Blue, id_size=>id_small, id_option=>id_val_a, ...)
Returns
int
Exceptions
RestException 500
RestException 401
RestException 404
@url POST ref/{ref}/variants
Definition at line 1742 of file api_products.class.php.
delete()
delete ($id)
Delete product.
Parameters
int $id Product ID
Returns
array
Definition at line 420 of file api_products.class.php.
deleteAttributes()
deleteAttributes ($id)
Delete attributes by id.
Parameters
int $id ID of Attribute
Returns
int Result of deletion
Exceptions
RestException 500
RestException 401
@url DELETE attributes/{id}
Definition at line 1272 of file api_products.class.php.
deleteAttributeValueById()
deleteAttributeValueById ($id)
Delete attribute value by id.
Parameters
int $id ID of Attribute value
Returns
int
Exceptions
RestException 500
RestException 401
@url DELETE attributes/values/{id}
Definition at line 1579 of file api_products.class.php.
deleteAttributeValueByRef()
deleteAttributeValueByRef ($id, $ref)
Delete attribute value by ref.
Parameters
int $id ID of Attribute
string $ref Ref of Attribute value
Returns
int
Exceptions
RestException 401
@url DELETE attributes/{id}/values/ref/{ref}
Definition at line 1384 of file api_products.class.php.
deletePurchasePrice()
deletePurchasePrice ($id, $priceid)
Delete purchase price for a product.
Parameters
int $id Product ID
int $priceid purchase price ID
@url DELETE {id}/purchase_prices/{priceid}
Returns
int
Exceptions
RestException 401
RestException 404
Definition at line 791 of file api_products.class.php.
deleteVariant()
deleteVariant ($id)
Delete product variants.
Parameters
int $id ID of Variant
Returns
int Result of deletion
Exceptions
RestException 500
RestException 401
@url DELETE variants/{id}
Definition at line 1830 of file api_products.class.php.
delSubproducts()
delSubproducts ($id, $subproduct_id)
Remove subproduct.
Unlink a product/service from a parent product/service
Parameters
int $id Id of parent product/service
int $subproduct_id Id of child product/service
Returns
int
Exceptions
RestException 401
RestException 404
@url DELETE {id}/subproducts/remove/{subproduct_id}
Definition at line 521 of file api_products.class.php.
get()
get ($id, $includestockdata = 0, $includesubproducts = false, $includeparentid = false, $includetrans = false)
Get properties of a product object by id.
Return an array with product information.
Parameters
int $id ID of product
int $includestockdata Load also information about stock (slower)
bool $includesubproducts Load information about subproducts
bool $includeparentid Load also ID of parent product (if product is a variant of a parent product)
bool $includetrans Load also the translations of product label and description
Returns
array|mixed Data without useless information
Exceptions
RestException 401
RestException 403
RestException 404
Definition at line 83 of file api_products.class.php.
getAttributeById()
getAttributeById ($id)
Get attribute by ID.
Parameters
int $id ID of Attribute
Returns
array
Exceptions
RestException 401
RestException 404
@url GET attributes/{id}
Definition at line 1057 of file api_products.class.php.
getAttributes()
getAttributes ($sortfield = "t.ref", $sortorder = 'ASC', $limit = 100, $page = 0, $sqlfilters = '')
Get attributes.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.ref:like:color)"
Returns
array
Exceptions
RestException 401
RestException 404
RestException 503
@url GET attributes
Definition at line 991 of file api_products.class.php.
getAttributesByRef()
getAttributesByRef ($ref)
Get attributes by ref.
Parameters
string $ref Reference of Attribute
Returns
array
Exceptions
RestException 401
RestException 404
@url GET attributes/ref/{ref}
Definition at line 1100 of file api_products.class.php.
getAttributesByRefExt()
getAttributesByRefExt ($ref_ext)
Get attributes by ref_ext.
Parameters
string $ref_ext External reference of Attribute
Returns
array
Exceptions
RestException 500
RestException 401
@url GET attributes/ref_ext/{ref_ext}
Definition at line 1147 of file api_products.class.php.
getAttributeValueById()
getAttributeValueById ($id)
Get attribute value by id.
Parameters
int $id ID of Attribute value
Returns
array
Exceptions
RestException 500
RestException 401
@url GET attributes/values/{id}
Definition at line 1300 of file api_products.class.php.
getAttributeValueByRef()
getAttributeValueByRef ($id, $ref)
Get attribute value by ref.
Parameters
int $id ID of Attribute value
string $ref Ref of Attribute value
Returns
array
Exceptions
RestException 500
RestException 401
@url GET attributes/{id}/values/ref/{ref}
Definition at line 1341 of file api_products.class.php.
getAttributeValues()
getAttributeValues ($id)
Get all values for an attribute id.
Parameters
int $id ID of an Attribute
Returns
array
Exceptions
RestException 401
RestException 500
@url GET attributes/{id}/values
Definition at line 1427 of file api_products.class.php.
getAttributeValuesByRef()
getAttributeValuesByRef ($ref)
Get all values for an attribute ref.
Parameters
string $ref Ref of an Attribute
Returns
array
Exceptions
RestException 401
@url GET attributes/ref/{ref}/values
Definition at line 1458 of file api_products.class.php.
getByBarcode()
getByBarcode ($barcode, $includestockdata = 0, $includesubproducts = false, $includeparentid = false, $includetrans = false)
Get properties of a product object by barcode.
Return an array with product information.
Parameters
string $barcode Barcode of element
int $includestockdata Load also information about stock (slower)
bool $includesubproducts Load information about subproducts
bool $includeparentid Load also ID of parent product (if product is a variant of a parent product)
bool $includetrans Load also the translations of product label and description
Returns
array|mixed Data without useless information
@url GET barcode/{barcode}
Exceptions
RestException 401
RestException 403
RestException 404
Definition at line 155 of file api_products.class.php.
References _fetch().
getByRef()
getByRef ($ref, $includestockdata = 0, $includesubproducts = false, $includeparentid = false, $includetrans = false)
Get properties of a product object by ref.
Return an array with product information.
Parameters
string $ref Ref of element
int $includestockdata Load also information about stock (slower)
bool $includesubproducts Load information about subproducts
bool $includeparentid Load also ID of parent product (if product is a variant of a parent product)
bool $includetrans Load also the translations of product label and description
Returns
array|mixed Data without useless information
@url GET ref/{ref}
Exceptions
RestException 401
RestException 403
RestException 404
Definition at line 107 of file api_products.class.php.
getByRefExt()
getByRefExt ($ref_ext, $includestockdata = 0, $includesubproducts = false, $includeparentid = false, $includetrans = false)
Get properties of a product object by ref_ext.
Return an array with product information.
Parameters
string $ref_ext Ref_ext of element
int $includestockdata Load also information about stock (slower)
bool $includesubproducts Load information about subproducts
bool $includeparentid Load also ID of parent product (if product is a variant of a parent product)
bool $includetrans Load also the translations of product label and description
Returns
array|mixed Data without useless information
@url GET ref_ext/{ref_ext}
Exceptions
RestException 401
RestException 403
RestException 404
Definition at line 131 of file api_products.class.php.
References _fetch().
getCategories()
getCategories ($id, $sortfield = "s.rowid", $sortorder = 'ASC', $limit = 0, $page = 0)
Get categories for a product.
Parameters
int $id ID of product
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
Returns
mixed
@url GET {id}/categories
Definition at line 552 of file api_products.class.php.
getCustomerPricesPerCustomer()
getCustomerPricesPerCustomer ($id, $thirdparty_id = '')
Get prices per customer for a product.
Parameters
int $id ID of product
string $thirdparty_id Thirdparty id to filter orders of (example '1') {@pattern /^[0-9,]*$/i}
Returns
mixed
@url GET {id}/selling_multiprices/per_customer
Definition at line 624 of file api_products.class.php.
getCustomerPricesPerQuantity()
getCustomerPricesPerQuantity ($id)
Get prices per quantity for a product.
Parameters
int $id ID of product
Returns
mixed
@url GET {id}/selling_multiprices/per_quantity
Definition at line 673 of file api_products.class.php.
getCustomerPricesPerSegment()
getCustomerPricesPerSegment ($id)
Get prices per segment for a product.
Parameters
int $id ID of product
Returns
mixed
@url GET {id}/selling_multiprices/per_segment
Definition at line 582 of file api_products.class.php.
getPurchasePrices()
getPurchasePrices ($id, $ref = '', $ref_ext = '', $barcode = '')
Get purchase prices for a product.
Return an array with product information. TODO implement getting a product by ref or by $ref_ext
Parameters
int $id ID of product
string $ref Ref of element
string $ref_ext Ref ext of element
string $barcode Barcode of element
Returns
array|mixed Data without useless information
@url GET {id}/purchase_prices
Exceptions
RestException 401
RestException 403
RestException 404
Definition at line 938 of file api_products.class.php.
getStock()
getStock ($id, $selected_warehouse_id = null)
Get stock data for the product id given.
Optionaly with $selected_warehouse_id parameter user can get stock of specific warehouse
Parameters
int $id ID of Product
int $selected_warehouse_id ID of warehouse
Returns
int
Exceptions
RestException 500
RestException 401
RestException 404
@url GET {id}/stock
Definition at line 1859 of file api_products.class.php.
getSubproducts()
getSubproducts ($id)
Get the list of subproducts of the product.
Parameters
int $id Id of parent product/service
Returns
array
Exceptions
RestException
RestException 401
RestException 404
@url GET {id}/subproducts
Definition at line 453 of file api_products.class.php.
getSupplierProducts()
getSupplierProducts ($sortfield = "t.ref", $sortorder = 'ASC', $limit = 100, $page = 0, $mode = 0, $category = 0, $supplier = 0, $sqlfilters = '')
Get a list of all purchase prices of products.
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
int $mode Use this param to filter list (0 for all, 1 for only product, 2 for only service)
int $category Use this param to filter list by category of product
int $supplier Use this param to filter list by supplier
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.tobuy:=:0) and (t.tosell:=:1)"
Returns
array Array of product objects
@url GET purchase_prices
Definition at line 828 of file api_products.class.php.
getVariants()
getVariants ($id, $includestock = 0)
Get product variants.
Parameters
int $id ID of Product
int $includestock Default value 0. If parameter is set to 1 the response will contain stock data of each variant
Returns
array
Exceptions
RestException 500
RestException 401
@url GET {id}/variants
Definition at line 1606 of file api_products.class.php.
getVariantsByProdRef()
getVariantsByProdRef ($ref)
Get product variants by Product ref.
Parameters
string $ref Ref of Product
Returns
array
Exceptions
RestException 500
RestException 401
@url GET ref/{ref}/variants
Definition at line 1642 of file api_products.class.php.
index()
index ($sortfield = "t.ref", $sortorder = 'ASC', $limit = 100, $page = 0, $mode = 0, $category = 0, $sqlfilters = '', $ids_only = false, $variant_filter = 0, $pagination_data = false)
List products.
Get a list of products
Parameters
string $sortfield Sort field
string $sortorder Sort order
int $limit Limit for list
int $page Page number
int $mode Use this param to filter list (0 for all, 1 for only product, 2 for only service)
int $category Use this param to filter list by category
string $sqlfilters Other criteria to filter answers separated by a comma. Syntax example "(t.tobuy:=:0) and (t.tosell:=:1)"
bool $ids_only Return only IDs of product instead of all properties (faster, above all if list is long)
int $variant_filter Use this param to filter list (0 = all, 1=products without variants, 2=parent of variants, 3=variants only)
bool $pagination_data If this parameter is set to true the response will include pagination data. Default value is false. Page starts from 0
Returns
array Array of product objects
Definition at line 177 of file api_products.class.php.
post()
post ($request_data = null)
Create product object.
Parameters
array $request_data Request data
Returns
int ID of product
Definition at line 292 of file api_products.class.php.
put()
put ($id, $request_data = null)
Update product.
Price will be updated by this API only if option is set on "One price per product". See other APIs for other price modes.
Parameters
int $id Id of product to update
array $request_data Datas
Returns
int
Exceptions
RestException 401
RestException 404
Definition at line 321 of file api_products.class.php.
putAttributes()
putAttributes ($id, $request_data = null)
Update attributes by id.
Parameters
int $id ID of Attribute
array $request_data Datas
Returns
array
Exceptions
RestException
RestException 401
RestException 404
@url PUT attributes/{id}
Definition at line 1226 of file api_products.class.php.
putAttributeValue()
putAttributeValue ($id, $request_data)
Update attribute value.
Parameters
int $id ID of Attribute
array $request_data Datas
Returns
array
Exceptions
RestException 401
RestException 500
@url PUT attributes/values/{id}
Definition at line 1533 of file api_products.class.php.
putVariant()
putVariant ($id, $request_data = null)
Put product variants.
Parameters
int $id ID of Variant
array $request_data Datas
Returns
int
Exceptions
RestException 500
RestException 401
@url PUT variants/{id}
Definition at line 1796 of file api_products.class.php.
Member Data Documentation
$FIELDS
$FIELDS static
Initial value:
= array(
        'ref',
        'label'
    )
Definition at line 40 of file api_products.class.php.
The documentation for this class was generated from the following file:
htdocs/product/class/api_products.class.php