Dolibarr: SupplierProposal Class Reference
SupplierProposal Class Reference
Class to manage price ask supplier.
Public Member Functions
__construct ($db, $socid="", $supplier_proposalid=0)
Constructor.
add_product ($idproduct, $qty, $remise_percent=0)
Add line into array ->lines.
insert_discount ($idremise)
Adding line of fixed discount in the proposal in DB.
addline ($desc, $pu_ht, $qty, $txtva, $txlocaltax1=0, $txlocaltax2=0, $fk_product=0, $remise_percent=0, $price_base_type='HT', $pu_ttc=0, $info_bits=0, $type=0, $rang=-1, $special_code=0, $fk_parent_line=0, $fk_fournprice=0, $pa_ht=0, $label='', $array_options=0, $ref_supplier='', $fk_unit='', $origin='', $origin_id=0, $pu_ht_devise=0, $date_start=0, $date_end=0)
Add a proposal line into database (linked to product/service or not) Les parametres sont deja cense etre juste et avec valeurs finales a l'appel de cette methode.
updateline ($rowid, $pu, $qty, $remise_percent, $txtva, $txlocaltax1=0, $txlocaltax2=0, $desc='', $price_base_type='HT', $info_bits=0, $special_code=0, $fk_parent_line=0, $skip_update_total=0, $fk_fournprice=0, $pa_ht=0, $label='', $type=0, $array_options=0, $ref_supplier='', $fk_unit='', $pu_ht_devise=0)
Update a proposal line.
deleteline ($lineid)
Delete detail line.
create ($user, $notrigger=0)
Create commercial proposal into database this->ref can be set or empty.
createFromClone (User $user, $fromid=0)
Load an object from its id and create a new one in database.
fetch ($rowid, $ref='')
Load a proposal from database and its ligne array.
valid ($user, $notrigger=0)
Set status to validated.
set_date_livraison ($user, $delivery_date)
Set delivery date.
setDeliveryDate ($user, $delivery_date)
Set delivery date.
set_remise_percent ($user, $remise)
Set an overall discount on the proposal.
set_remise_absolue ($user, $remise)
Set an absolute overall discount on the proposal.
reopen ($user, $statut, $note='', $notrigger=0)
Reopen the commercial proposal.
cloture ($user, $status, $note)
Close the askprice.
updateOrCreatePriceFournisseur ($user)
Add or update supplier price according to result of proposal.
updatePriceFournisseur ($idProductFournPrice, $product, $user)
Upate ProductFournisseur.
createPriceFournisseur ($product, $user)
Create ProductFournisseur.
setDraft ($user)
Set draft status.
liste_array ($shortlist=0, $draft=0, $notcurrentuser=0, $socid=0, $limit=0, $offset=0, $sortfield='p.datec', $sortorder='DESC')
Return list of askprice (eventually filtered on user) into an array.
delete ($user, $notrigger=0)
Delete askprice.
info ($id)
Object SupplierProposal Information.
getLibStatut ($mode=0)
Return label of status of proposal (draft, validated, ...)
LibStatut ($status, $mode=1)
Return label of a status (draft, validated, ...)
load_board ($user, $mode)
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
initAsSpecimen ()
Initialise an instance with random values.
load_state_board ()
Load indicator this->nb of global stats widget.
getNextNumRef ($soc)
Returns the reference to the following non used Proposal used depending on the active numbering module defined into SUPPLIER_PROPOSAL_ADDON.
getNomUrl ($withpicto=0, $option='', $get_params='', $notooltip=0, $save_lastsearch_value=-1, $addlinktonotes=0)
Return clicable link of object (with eventually picto)
getLinesArray ()
Retrieve an array of supplier proposal lines.
generateDocument ($modele, $outputlangs, $hidedetails=0, $hidedesc=0, $hideref=0, $moreparams=null)
Create a document onto disk according to template module.
Public Member Functions inherited from CommonObject
errorsToString ()
Method to output saved errors.
getFormatedCustomerRef ($objref)
Return customer ref for screen output.
getFormatedSupplierRef ($objref)
Return supplier ref for screen output.
getFullName ($langs, $option=0, $nameorder=-1, $maxlen=0)
Return full name (civility+' '+name+' '+lastname)
setUpperOrLowerCase ()
Set to upper or ucwords/lower if needed.
getKanbanView ($option='')
Return clicable link of object (with eventually picto)
getFullAddress ($withcountry=0, $sep="\n", $withregion=0, $extralangcode='')
Return full address of contact.
getBannerAddress ($htmlkey, $object)
Return full address for banner.
getLastMainDocLink ($modulepart, $initsharekey=0, $relativelink=0)
Return the link of last main doc file for direct public download.
add_contact ($fk_socpeople, $type_contact, $source='external', $notrigger=0)
Add a link between element $this->element and a contact.
copy_linked_contact ($objFrom, $source='internal')
Copy contact from one element to current.
update_contact ($rowid, $statut, $type_contact_id=0, $fk_socpeople=0)
Update a link to contact line.
delete_contact ($rowid, $notrigger=0)
Delete a link to contact line.
delete_linked_contact ($source='', $code='')
Delete all links between an object $this and all its contacts.
liste_contact ($status=-1, $source='external', $list=0, $code='')
Get array of all contacts for an object.
swapContactStatus ($rowid)
Update status of a contact linked to object.
liste_type_contact ($source='internal', $order='position', $option=0, $activeonly=0, $code='')
Return array with list of possible values for type of contacts.
listeTypeContacts ($source='internal', $option=0, $activeonly=0, $code='', $element='', $excludeelement='')
Return array with list of possible values for type of contacts.
getIdContact ($source, $code, $status=0)
Return id of contacts for a source and a contact code.
fetch_contact ($contactid=null)
Load object contact with id=$this->contact_id into $this->contact.
fetch_thirdparty ($force_thirdparty_id=0)
Load the third party of object, from id $this->socid or $this->fk_soc, into this->thirdparty.
fetchOneLike ($ref)
Looks for an object with ref matching the wildcard provided It does only work when $this->table_ref_field is set.
fetch_barcode ()
Load data for barcode into properties ->barcode_type* Properties ->barcode_type that is id of barcode.
fetch_project ()
Load the project with id $this->fk_project into this->project.
fetch_projet ()
Load the project with id $this->fk_project into this->project.
fetch_product ()
Load the product with id $this->fk_product into this->product.
fetch_user ($userid)
Load the user with id $userid into this->user.
fetch_origin ()
Read linked origin object.
fetchObjectFrom ($table, $field, $key, $element=null)
Load object from specific field.
getValueFrom ($table, $id, $field)
Getter generic.
setValueFrom ($field, $value, $table='', $id=null, $format='', $id_field='', $fuser=null, $trigkey='', $fk_user_field='fk_user_modif')
Setter generic.
load_previous_next_ref ($filter, $fieldid, $nodbprefix=0)
Load properties id_previous and id_next by comparing $fieldid with $this->ref.
getListContactId ($source='external')
Return list of id of contacts of object.
setProject ($projectid)
Link element with a project.
setPaymentMethods ($id)
Change the payments methods.
setMulticurrencyCode ($code)
Change the multicurrency code.
setMulticurrencyRate ($rate, $mode=1)
Change the multicurrency rate.
setPaymentTerms ($id)
Change the payments terms.
setTransportMode ($id)
Change the transport mode methods.
setRetainedWarrantyPaymentTerms ($id)
Change the retained warranty payments terms.
setDeliveryAddress ($id)
Define delivery address.
setShippingMethod ($shipping_method_id, $notrigger=false, $userused=null)
Change the shipping method.
setWarehouse ($warehouse_id)
Change the warehouse.
setDocModel ($user, $modelpdf)
Set last model used by doc generator.
setBankAccount ($fk_account, $notrigger=false, $userused=null)
Change the bank account.
line_order ($renum=false, $rowidorder='ASC', $fk_parent_line=true)
Save a new position (field rang) for details lines.
getChildrenOfLine ($id, $includealltree=0)
Get children of line.
line_up ($rowid, $fk_parent_line=true)
Update a line to have a lower rank.
line_down ($rowid, $fk_parent_line=true)
Update a line to have a higher rank.
updateRangOfLine ($rowid, $rang)
Update position of line (rang)
line_ajaxorder ($rows)
Update position of line with ajax (rang)
updateLineUp ($rowid, $rang)
Update position of line up (rang)
updateLineDown ($rowid, $rang, $max)
Update position of line down (rang)
getRangOfLine ($rowid)
Get position of line (rang)
getIdOfLine ($rang)
Get rowid of the line relative to its position.
line_max ($fk_parent_line=0)
Get max value used for position of line (rang)
update_ref_ext ($ref_ext)
Update external ref of element.
update_note ($note, $suffix='')
Update note of element.
update_note_public ($note)
update_price ($exclspec=0, $roundingadjust='none', $nodatabaseupdate=0, $seller=null)
Update total_ht, total_ttc, total_vat, total_localtax1, total_localtax2 for an object (sum of lines).
add_object_linked ($origin=null, $origin_id=null, $f_user=null, $notrigger=0)
Add objects linked in llx_element_element.
fetchObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $clause='OR', $alsosametype=1, $orderby='sourcetype', $loadalsoobjects=1)
Fetch array of objects linked to current object (object of enabled modules only).
updateObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $f_user=null, $notrigger=0)
Update object linked of a current object.
deleteObjectLinked ($sourceid=null, $sourcetype='', $targetid=null, $targettype='', $rowid='', $f_user=null, $notrigger=0)
Delete all links between an object $this.
setStatut ($status, $elementId=null, $elementType='', $trigkey='')
Set status of an object.
getCanvas ($id=0, $ref='')
Load type of canvas of an object if it exists.
getSpecialCode ($lineid)
Get special code of a line.
isObjectUsed ($id=0)
Function to check if an object is used by others.
hasProductsOrServices ($predefined=-1)
Function to say how many lines object contains.
getTotalDiscount ()
Function that returns the total amount HT of discounts applied for all lines.
getTotalWeightVolume ()
Return into unit=0, the calculated total of weight and volume of all lines * qty Calculate by adding weight and volume of each product line, so properties ->volume/volume_units/weight/weight_units must be loaded on line.
setExtraParameters ()
Set extra parameters.
formAddObjectLine ($dateSelector, $seller, $buyer, $defaulttpldir='/core/tpl')
Show add free and predefined products/services form.
printObjectLines ($action, $seller, $buyer, $selected=0, $dateSelector=0, $defaulttpldir='/core/tpl')
Return HTML table for object lines TODO Move this into an output class file (htmlline.class.php) If lines are into a template, title must also be into a template But for the moment we don't know if it's possible as we keep a method available on overloaded objects.
printObjectLine ($action, $line, $var, $num, $i, $dateSelector, $seller, $buyer, $selected=0, $extrafields=null, $defaulttpldir='/core/tpl')
Return HTML content of a detail line TODO Move this into an output class file (htmlline.class.php)
printOriginLinesList ($restrictlist='', $selectedLines=array())
Return HTML table table of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
printOriginLine ($line, $var, $restrictlist='', $defaulttpldir='/core/tpl', $selectedLines=array())
Return HTML with a line of table array of source object lines TODO Move this and previous function into output html class file (htmlline.class.php).
add_element_resource ($resource_id, $resource_type, $busy=0, $mandatory=0)
Add resources to the current object : add entry into llx_element_resources Need $this->element & $this->id.
delete_resource ($rowid, $element, $notrigger=0)
Delete a link to resource line.
__clone ()
Overwrite magic function to solve problem of cloning object that are kept as references.
addThumbs ($file)
Build thumb.
getDefaultCreateValueFor ($fieldname, $alternatevalue=null)
Return the default value to use for a field when showing the create form of object.
call_trigger ($triggerName, $user)
Call trigger based on this instance.
fetchValuesForExtraLanguages ()
Function to get alternative languages of a data into $this->array_languages This method is NOT called by method fetch of objects but must be called separately.
setValuesForExtraLanguages ($onlykey='')
Fill array_options property of object by extrafields value (using for data sent by forms)
fetchNoCompute ($id)
Function to make a fetch but set environment to avoid to load computed values before.
fetch_optionals ($rowid=null, $optionsArray=null)
Function to get extra fields of an object into $this->array_options This method is in most cases called by method fetch of objects but you can call it separately.
deleteExtraFields ()
Delete all extra fields values for the current object.
insertExtraFields ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
insertExtraLanguages ($trigger='', $userused=null)
Add/Update all extra fields values for the current object.
updateExtraField ($key, $trigger=null, $userused=null)
Update 1 extra field value for the current object.
updateExtraLanguages ($key, $trigger=null, $userused=null)
Update an extra language value for the current object.
showInputField ($val, $key, $value, $moreparam='', $keysuffix='', $keyprefix='', $morecss=0, $nonewbutton=0)
Return HTML string to put an input field into a page Code very similar with showInputField of extra fields.
showOutputField ($val, $key, $value, $moreparam='', $keysuffix='', $keyprefix='', $morecss='')
Return HTML string to show a field into a page Code very similar with showOutputField of extra fields.
showOptionals ($extrafields, $mode='view', $params=null, $keysuffix='', $keyprefix='', $onetrtd=0, $display_type='card')
Function to show lines of extrafields with output datas.
getJSListDependancies ($type='_extra')
getRights ()
Returns the rights used for this class.
defineBuyPrice ($unitPrice=0.0, $discountPercent=0.0, $fk_product=0)
Get buy price to use for margin calculation.
show_photos ($modulepart, $sdir, $size=0, $nbmax=0, $nbbyrow=5, $showfilename=0, $showaction=0, $maxHeight=120, $maxWidth=160, $nolink=0, $notitle=0, $usesharelink=0)
Show photos of an object (nbmax maximum), into several columns.
isDate ($info)
Function test if type is date.
isDuration ($info)
Function test if type is duration.
isInt ($info)
Function test if type is integer.
isFloat ($info)
Function test if type is float.
isText ($info)
Function test if type is text.
setVarsFromFetchObj (&$obj)
Function to load data from a SQL pointer into properties of current object $this.
getFieldList ($alias='')
Function to concat keys of fields.
createCommon (User $user, $notrigger=false)
Create object into database.
fetchCommon ($id, $ref=null, $morewhere='')
Load object in memory from the database.
fetchLinesCommon ($morewhere='')
Load object in memory from the database.
updateCommon (User $user, $notrigger=false)
Update object into database.
deleteCommon (User $user, $notrigger=false, $forcechilddeletion=0)
Delete object in database.
deleteByParentField ($parentId=0, $parentField='')
Delete all child object from a parent ID.
deleteLineCommon (User $user, $idline, $notrigger=false)
Delete a line of object in database.
setStatusCommon ($user, $status, $notrigger=0, $triggercode='')
Set to a status.
initAsSpecimenCommon ()
Initialise object with example values Id must be 0 if object instance is a specimen.
fetchComments ()
Load comments linked with current task.
getNbComments ()
Return nb comments already posted.
trimParameters ($parameters)
Trim object parameters.
getCategoriesCommon ($type_categ)
Sets object to given categories.
setCategoriesCommon ($categories, $type_categ='', $remove_existing=true)
Sets object to given categories.
cloneCategories ($fromId, $toId, $type='')
Copy related categories to another object.
deleteEcmFiles ($mode=0)
Delete related files of object in database.
Static Public Member Functions
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id)
Function used to replace a thirdparty id with another one.
Static Public Member Functions inherited from CommonObject
static isExistingObject ($element, $id, $ref='', $ref_ext='')
Check an object id/ref exists If you don't need/want to instantiate object and just need to know if object exists, use this method instead of fetch.
static getAllItemsLinkedByObjectID ($fk_object_where, $field_select, $field_where, $table_element)
Function used to get an array with all items linked to an object id in association table.
static deleteAllItemsLinkedByObjectID ($fk_object_where, $field_where, $table_element)
Function used to remove all items linked to an object id in association table.
static commonReplaceThirdparty (DoliDB $db, $origin_id, $dest_id, array $tables, $ignoreerrors=0)
Function used to replace a thirdparty id with another one.
Public Attributes
$element = 'supplier_proposal'
$table_element = 'supplier_proposal'
$table_element_line = 'supplier_proposaldet'
$fk_element = 'fk_supplier_proposal'
$picto = 'supplier_proposal'
$ismultientitymanaged = 1
$restrictiononfksoc = 1
$socid
$author
$ref_fourn
$ref_supplier
$statut
$date
$date_livraison
$delivery_date
$datec
$date_creation
$datev
$date_validation
$user_author_id
$user_valid_id
$user_close_id
$price
$tva
$total
$cond_reglement_code
$mode_reglement_code
$remise = 0
$remise_percent = 0
$remise_absolue = 0
$extraparams = array()
$lines = array()
$line
$labelStatus = array()
$labelStatusShort = array()
$nbtodo
$nbtodolate
$fk_multicurrency
$multicurrency_code
$multicurrency_tx
$multicurrency_total_ht
$multicurrency_total_tva
$multicurrency_total_ttc
const STATUS_DRAFT = 0
Draft status.
const STATUS_VALIDATED = 1
Validated status.
const STATUS_SIGNED = 2
Signed quote.
const STATUS_NOTSIGNED = 3
Not signed quote, canceled.
const STATUS_CLOSE = 4
Billed or closed/processed quote.
Public Attributes inherited from CommonObject
$db
$id
$entity
$error
$errorhidden
$errors = array()
$element
$table_element
$table_element_line = ''
$import_key
$array_options = array()
$array_languages = null
$linkedObjectsIds
$linkedObjects
$oldcopy
$context = array()
$canvas
$project
$fk_project
$projet
$contact
$contact_id
$thirdparty
$user
$origin
$origin_id
$ref
$ref_ext
$ref_previous
$ref_next
$newref
$statut
$status
$country
$country_id
$country_code
$state
$state_id
$state_code
$region_id
$region_code
$region
$barcode_type
$barcode_type_code
$barcode_type_label
$barcode_type_coder
$mode_reglement_id
$cond_reglement_id
$demand_reason_id
$transport_mode_id
$cond_reglement
$fk_delivery_address
$shipping_method_id
$model_pdf
$modelpdf
$last_main_doc
$fk_bank
$fk_account
$openid
$note_public
$note_private
$note
$total_ht
$total_tva
$total_localtax1
$total_localtax2
$total_ttc
$lines
$comments = array()
$name
$lastname
$firstname
$civility_id
$date_creation
$date_validation
$date_modification
$next_prev_filter
$specimen = 0
$sendtoid
$alreadypaid
Protected Attributes
$table_ref_field = 'ref'
{}
Protected Attributes inherited from CommonObject
$table_ref_field = ''
$childtables = array()
$childtablesoncascade = array()
Additional Inherited Members
Protected Member Functions inherited from CommonObject
commonGenerateDocument ($modelspath, $modele, $outputlangs, $hidedetails, $hidedesc, $hideref, $moreparams=null)
Common function for all objects extending CommonObject for generating documents.
isArray ($info)
Function test if type is array.
canBeNull ($info)
Function test if field can be null.
isForcedToNullIfZero ($info)
Function test if field is forced to null if zero or empty.
isIndex ($info)
Function test if is indexed.
setSaveQuery ()
Function to prepare a part of the query for insert.
quote ($value, $fieldsentry)
Add quote to field value if necessary.
Detailed Description
Class to manage price ask supplier.
Definition at line 49 of file supplier_proposal.class.php.
Constructor & Destructor Documentation
__construct()
__construct ($db, $socid = "", $supplier_proposalid = 0)
Constructor.
Parameters
DoliDB $db Database handler
int $socid Id third party
int $supplier_proposalid Id supplier_proposal
Definition at line 230 of file supplier_proposal.class.php.
Member Function Documentation
add_product()
add_product ($idproduct, $qty, $remise_percent = 0)
Add line into array ->lines.
Parameters
int $idproduct Product Id to add
int $qty Quantity
int $remise_percent Discount effected on Product
Returns
int <0 if KO, >0 if OK
TODO Remplacer les appels a cette fonction par generation objet Ligne
Definition at line 252 of file supplier_proposal.class.php.
addline()
addline ($desc, $pu_ht, $qty, $txtva, $txlocaltax1 = 0, $txlocaltax2 = 0, $fk_product = 0, $remise_percent = 0, $price_base_type = 'HT', $pu_ttc = 0, $info_bits = 0, $type = 0, $rang = -1, $special_code = 0, $fk_parent_line = 0, $fk_fournprice = 0, $pa_ht = 0, $label = '', $array_options = 0, $ref_supplier = '', $fk_unit = '', $origin = '', $origin_id = 0, $pu_ht_devise = 0, $date_start = 0, $date_end = 0)
Add a proposal line into database (linked to product/service or not) Les parametres sont deja cense etre juste et avec valeurs finales a l'appel de cette methode.
Aussi, pour le taux tva, il doit deja avoir ete defini par l'appelant par la methode get_default_tva(societe_vendeuse,societe_acheteuse,'',produit) et le desc doit deja avoir la bonne valeur (a l'appelant de gerer le multilangue)
Parameters
string $desc Description de la ligne
double $pu_ht Prix unitaire
double $qty Quantite
double $txtva Taux de tva
double $txlocaltax1 Local tax 1 rate
double $txlocaltax2 Local tax 2 rate
int $fk_product Product/Service ID predefined
double $remise_percent Percentage discount of the line
string $price_base_type HT or TTC
double $pu_ttc Prix unitaire TTC
int $info_bits Bits of type of lines
int $type Type of line (product, service)
int $rang Position of line
int $special_code Special code (also used by externals modules!)
int $fk_parent_line Id of parent line
int $fk_fournprice Id supplier price. If 0, we will take best price. If -1 we keep it empty.
int $pa_ht Buying price without tax
string $label ???
array $array_options extrafields array
string $ref_supplier Supplier price reference
int $fk_unit Id of the unit to use.
string $origin 'order', 'supplier_proposal', ...
int $origin_id Id of origin line
double $pu_ht_devise Amount in currency
int $date_start Date start
int $date_end Date end
Returns
int >0 if OK, <0 if KO
See also
add_product()
Definition at line 400 of file supplier_proposal.class.php.
cloture()
cloture ($user, $status, $note)
Close the askprice.
Parameters
User $user Object user that close
int $status Status
string $note Comment
Returns
int <0 if KO, >0 if OK
Definition at line 1670 of file supplier_proposal.class.php.
create()
create ($user, $notrigger = 0)
Create commercial proposal into database this->ref can be set or empty.
If empty, we will use "(PROVid)"
Parameters
User $user User that create
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >=0 if OK
Definition at line 864 of file supplier_proposal.class.php.
createFromClone()
createFromClone (User $user, $fromid = 0)
Load an object from its id and create a new one in database.
Parameters
User $user User making the clone
int $fromid Id of thirdparty
Returns
int New id of clone
Definition at line 1097 of file supplier_proposal.class.php.
createPriceFournisseur()
createPriceFournisseur ($product, $user)
Create ProductFournisseur.
Parameters
Product $product Object Product
User $user Object user
Returns
int <0 if KO, >0 if OK
Definition at line 1807 of file supplier_proposal.class.php.
delete()
delete ($user, $notrigger = 0)
Delete askprice.
Parameters
User $user Object user that delete
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int 1 if ok, otherwise if error
Definition at line 1998 of file supplier_proposal.class.php.
deleteline()
deleteline ($lineid)
Delete detail line.
Parameters
int $lineid Id of line to delete
Returns
int >0 if OK, <0 if KO
Definition at line 835 of file supplier_proposal.class.php.
fetch()
fetch ($rowid, $ref = '')
Load a proposal from database and its ligne array.
Parameters
int $rowid id of object to load
string $ref Ref of proposal
Returns
int >0 if OK, <0 if KO
Definition at line 1187 of file supplier_proposal.class.php.
generateDocument()
generateDocument ($modele, $outputlangs, $hidedetails = 0, $hidedesc = 0, $hideref = 0, $moreparams = null)
Create a document onto disk according to template module.
Parameters
string $modele Force model to use ('' to not force)
Translate $outputlangs Object langs to use for output
int $hidedetails Hide details of lines
int $hidedesc Hide description
int $hideref Hide ref
null | array $moreparams Array to provide more information
Returns
int 0 if KO, 1 if OK
Definition at line 2643 of file supplier_proposal.class.php.
getLibStatut()
getLibStatut ($mode = 0)
Return label of status of proposal (draft, validated, ...)
Parameters
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto
Returns
string Label
Definition at line 2151 of file supplier_proposal.class.php.
getLinesArray()
getLinesArray ()
Retrieve an array of supplier proposal lines.
Returns
int >0 if OK, <0 if KO
Definition at line 2555 of file supplier_proposal.class.php.
getNextNumRef()
getNextNumRef ($soc)
Returns the reference to the following non used Proposal used depending on the active numbering module defined into SUPPLIER_PROPOSAL_ADDON.
Parameters
Societe $soc Object thirdparty
Returns
string Reference libre pour la propale
Definition at line 2408 of file supplier_proposal.class.php.
getNomUrl()
getNomUrl ($withpicto = 0, $option = '', $get_params = '', $notooltip = 0, $save_lastsearch_value = -1, $addlinktonotes = 0)
Return clicable link of object (with eventually picto)
Parameters
int $withpicto Add picto into link
string $option Where point the link ('compta', 'expedition', 'document', ...)
string $get_params Parametres added to url
int $notooltip 1=Disable tooltip
int $save_lastsearch_value -1=Auto, 0=No save of lastsearch_values when clicking, 1=Save lastsearch_values whenclicking
int $addlinktonotes Add link to show notes
Returns
string String with URL
Definition at line 2461 of file supplier_proposal.class.php.
info()
info ($id)
Object SupplierProposal Information.
Parameters
int $id Proposal id
Returns
void
Definition at line 2102 of file supplier_proposal.class.php.
initAsSpecimen()
initAsSpecimen ()
Initialise an instance with random values.
Used to build previews or test instances. id must be 0 if object instance is a specimen.
Returns
void
Definition at line 2288 of file supplier_proposal.class.php.
insert_discount()
insert_discount ($idremise)
Adding line of fixed discount in the proposal in DB.
Parameters
int $idremise Id of fixed discount
Returns
int >0 if OK, <0 if KO
Definition at line 305 of file supplier_proposal.class.php.
LibStatut()
LibStatut ($status, $mode = 1)
Return label of a status (draft, validated, ...)
Parameters
int $status Id status
int $mode 0=long label, 1=short label, 2=Picto + short label, 3=Picto, 4=Picto + long label, 5=Short label + Picto, 6=Long label + Picto
Returns
string Label
Definition at line 2164 of file supplier_proposal.class.php.
liste_array()
liste_array ($shortlist = 0, $draft = 0, $notcurrentuser = 0, $socid = 0, $limit = 0, $offset = 0, $sortfield = 'p.datec', $sortorder = 'DESC')
Return list of askprice (eventually filtered on user) into an array.
Parameters
int $shortlist 0=Return array[id]=ref, 1=Return array[](id=>id,ref=>ref,name=>name)
int $draft 0=not draft, 1=draft
int $notcurrentuser 0=all user, 1=not current user
int $socid Id third pary
int $limit For pagination
int $offset For pagination
string $sortfield Sort criteria
string $sortorder Sort order
Returns
int -1 if KO, array with result if OK
Definition at line 1928 of file supplier_proposal.class.php.
load_board()
load_board ($user, $mode)
Load indicators for dashboard (this->nbtodo and this->nbtodolate)
Parameters
User $user Object user
int $mode "opened" for askprice to close, "signed" for proposal to invoice
Returns
int <0 if KO, >0 if OK
Definition at line 2209 of file supplier_proposal.class.php.
load_state_board()
load_state_board ()
Load indicator this->nb of global stats widget.
Returns
int <0 if ko, >0 if ok
Definition at line 2367 of file supplier_proposal.class.php.
reopen()
reopen ($user, $statut, $note = '', $notrigger = 0)
Reopen the commercial proposal.
Parameters
User $user Object user that close
int $statut Statut
string $note Comment
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >0 if OK
Definition at line 1612 of file supplier_proposal.class.php.
replaceThirdparty()
static replaceThirdparty (DoliDB $db, $origin_id, $dest_id) static
Function used to replace a thirdparty id with another one.
Parameters
DoliDB $db Database handler
int $origin_id Old thirdparty id
int $dest_id New thirdparty id
Returns
bool
Definition at line 2674 of file supplier_proposal.class.php.
References CommonObject\commonReplaceThirdparty().
set_date_livraison()
set_date_livraison ($user, $delivery_date)
Set delivery date.
Parameters
User $user Object user that modify
int $delivery_date Delivery date
Returns
int <0 if ko, >0 if ok
Deprecated:
Use setDeliveryDate
Definition at line 1502 of file supplier_proposal.class.php.
References setDeliveryDate().
set_remise_absolue()
set_remise_absolue ($user, $remise)
Set an absolute overall discount on the proposal.
Parameters
User $user Object user that modify
double $remise Amount discount
Returns
int <0 if ko, >0 if ok
Definition at line 1575 of file supplier_proposal.class.php.
References price2num().
set_remise_percent()
set_remise_percent ($user, $remise)
Set an overall discount on the proposal.
Parameters
User $user Object user that modify
double $remise Amount discount
Returns
int <0 if ko, >0 if ok
Definition at line 1543 of file supplier_proposal.class.php.
References price2num().
setDeliveryDate()
setDeliveryDate ($user, $delivery_date)
Set delivery date.
Parameters
User $user Object user that modify
int $delivery_date Delivery date
Returns
int <0 if ko, >0 if ok
Definition at line 1515 of file supplier_proposal.class.php.
Referenced by set_date_livraison().
setDraft()
setDraft ($user)
Set draft status.
Parameters
User $user Object user that modify
Returns
int <0 if KO, >0 if OK
Definition at line 1870 of file supplier_proposal.class.php.
updateline()
updateline ($rowid, $pu, $qty, $remise_percent, $txtva, $txlocaltax1 = 0, $txlocaltax2 = 0, $desc = '', $price_base_type = 'HT', $info_bits = 0, $special_code = 0, $fk_parent_line = 0, $skip_update_total = 0, $fk_fournprice = 0, $pa_ht = 0, $label = '', $type = 0, $array_options = 0, $ref_supplier = '', $fk_unit = '', $pu_ht_devise = 0)
Update a proposal line.
Parameters
int $rowid Id de la ligne
double $pu Prix unitaire (HT ou TTC selon price_base_type)
double $qty Quantity
double $remise_percent Remise effectuee sur le produit
double $txtva Taux de TVA
double $txlocaltax1 Local tax 1 rate
double $txlocaltax2 Local tax 2 rate
string $desc Description
double $price_base_type HT ou TTC
int $info_bits Miscellaneous informations
int $special_code Special code (also used by externals modules!)
int $fk_parent_line Id of parent line (0 in most cases, used by modules adding sublevels into lines).
int $skip_update_total Keep fields total_xxx to 0 (used for special lines by some modules)
int $fk_fournprice Id of origin supplier price
int $pa_ht Price (without tax) of product when it was bought
string $label ???
int $type 0/1=Product/service
array $array_options extrafields array
string $ref_supplier Supplier price reference
int $fk_unit Id of the unit to use.
double $pu_ht_devise Unit price in currency
Returns
int 0 if OK, <0 if KO
Definition at line 676 of file supplier_proposal.class.php.
updateOrCreatePriceFournisseur()
updateOrCreatePriceFournisseur ($user)
Add or update supplier price according to result of proposal.
Parameters
User $user Object user
Returns
int > 0 if OK
Definition at line 1743 of file supplier_proposal.class.php.
updatePriceFournisseur()
updatePriceFournisseur ($idProductFournPrice, $product, $user)
Upate ProductFournisseur.
Parameters
int $idProductFournPrice id of llx_product_fournisseur_price
Product $product contain informations to update
User $user Object user
Returns
int <0 if KO, >0 if OK
Definition at line 1784 of file supplier_proposal.class.php.
valid()
valid ($user, $notrigger = 0)
Set status to validated.
Parameters
User $user Object user that validate
int $notrigger 1=Does not execute triggers, 0= execute triggers
Returns
int <0 if KO, >=0 if OK
Definition at line 1391 of file supplier_proposal.class.php.
Member Data Documentation
$author
$author
Deprecated:
See also
$user_author_id
Definition at line 101 of file supplier_proposal.class.php.
$datec
$datec
Deprecated:
See also
$date_creation
Definition at line 127 of file supplier_proposal.class.php.
$datev
$datev
Deprecated:
See also
$date_validation
Definition at line 138 of file supplier_proposal.class.php.
$price
$price
Deprecated:
See also
$price_ht
Definition at line 154 of file supplier_proposal.class.php.
$total
$total
Deprecated:
See also
$total_ttc
Definition at line 166 of file supplier_proposal.class.php.
$tva
$tva
Deprecated:
See also
$total_tva
Definition at line 160 of file supplier_proposal.class.php.
The documentation for this class was generated from the following file:
htdocs/supplier_proposal/class/supplier_proposal.class.php