Dolibarr: MyModuleFunctionalTest Class Reference
MyModuleFunctionalTest Class Reference
Public Member Functions
setUp ()
Unit test setup.
testEnableDeveloperMode ()
Test enabling developer mode.
testModuleEnabled ()
Test enabling the module.
testConfigurationPage ()
Test access to the configuration page.
testAboutPage ()
Test access to the about page.
testAboutPageRendersMarkdownReadme ()
Test about page is rendering Markdown.
testBoxDeclared ()
Test box is properly declared.
testTriggerDeclared ()
Test trigger is properly enabled.
testTriggerEnabled ()
Test trigger is properly declared.
tearDown ()
Unit test teardown.
Static Public Member Functions
static setUpBeforeClass ()
Global test setup.
static tearDownAfterClass ()
Global test teardown.
Static Public Attributes
static $browsers
Protected Member Functions
byHref ($value)
Helper function to select links by href.
assertPreConditions ()
Verify pre conditions.
assertPostConditions ()
Verify post conditions.
Static Protected Attributes
static $base_url = 'http://dev.zenfusion.fr'
static $dol_admin_user = 'admin'
static $dol_admin_pass = 'admin'
Private Member Functions
authenticate ()
Handle Dolibarr authentication.
Static Private Attributes
static $module_id = 500000
Detailed Description
Definition at line 44 of file MyModuleFunctionalTest.php.
Member Function Documentation
assertPostConditions()
assertPostConditions () protected
Verify post conditions.
Returns
void
Definition at line 285 of file MyModuleFunctionalTest.php.
assertPreConditions()
assertPreConditions () protected
Verify pre conditions.
Returns
void
Definition at line 122 of file MyModuleFunctionalTest.php.
authenticate()
authenticate () private
Handle Dolibarr authentication.
Returns
void
Definition at line 130 of file MyModuleFunctionalTest.php.
Referenced by MyModuleFunctionalTest\testAboutPage(), MyModuleFunctionalTest\testAboutPageRendersMarkdownReadme(), MyModuleFunctionalTest\testBoxDeclared(), MyModuleFunctionalTest\testConfigurationPage(), MyModuleFunctionalTest\testEnableDeveloperMode(), MyModuleFunctionalTest\testModuleEnabled(), MyModuleFunctionalTest\testTriggerDeclared(), and MyModuleFunctionalTest\testTriggerEnabled().
byHref()
byHref ($value) protected
Helper function to select links by href.
Parameters
string $value Href
Returns
mixed Helper string
Definition at line 88 of file MyModuleFunctionalTest.php.
Referenced by MyModuleFunctionalTest\testModuleEnabled().
setUp()
setUp ()
Unit test setup.
Returns
void
Definition at line 112 of file MyModuleFunctionalTest.php.
setUpBeforeClass()
static setUpBeforeClass () static
Global test setup.
Returns
void
Definition at line 104 of file MyModuleFunctionalTest.php.
tearDown()
tearDown ()
Unit test teardown.
Returns
void
Definition at line 293 of file MyModuleFunctionalTest.php.
tearDownAfterClass()
static tearDownAfterClass () static
Global test teardown.
Returns
void
Definition at line 301 of file MyModuleFunctionalTest.php.
testAboutPage()
testAboutPage ()
Test access to the about page.
@depends testConfigurationPage
Returns
bool
Definition at line 210 of file MyModuleFunctionalTest.php.
References MyModuleFunctionalTest\authenticate().
testAboutPageRendersMarkdownReadme()
testAboutPageRendersMarkdownReadme ()
Test about page is rendering Markdown.
@depends testAboutPage
Returns
bool
Definition at line 223 of file MyModuleFunctionalTest.php.
References MyModuleFunctionalTest\authenticate().
testBoxDeclared()
testBoxDeclared ()
Test box is properly declared.
@depends testModuleEnabled
Returns
bool
Definition at line 240 of file MyModuleFunctionalTest.php.
References MyModuleFunctionalTest\authenticate().
testConfigurationPage()
testConfigurationPage ()
Test access to the configuration page.
@depends testModuleEnabled
Returns
bool
Definition at line 197 of file MyModuleFunctionalTest.php.
References MyModuleFunctionalTest\authenticate().
testEnableDeveloperMode()
testEnableDeveloperMode ()
Test enabling developer mode.
Returns
bool
Definition at line 151 of file MyModuleFunctionalTest.php.
References MyModuleFunctionalTest\authenticate().
testModuleEnabled()
testModuleEnabled ()
Test enabling the module.
@depends testEnableDeveloperMode
Returns
bool
Definition at line 171 of file MyModuleFunctionalTest.php.
References MyModuleFunctionalTest\authenticate(), and MyModuleFunctionalTest\byHref().
testTriggerDeclared()
testTriggerDeclared ()
Test trigger is properly enabled.
@depends testModuleEnabled
Returns
bool
Definition at line 253 of file MyModuleFunctionalTest.php.
References MyModuleFunctionalTest\authenticate().
testTriggerEnabled()
testTriggerEnabled ()
Test trigger is properly declared.
@depends testTriggerDeclared
Returns
bool
Definition at line 270 of file MyModuleFunctionalTest.php.
References MyModuleFunctionalTest\authenticate().
Member Data Documentation
$browsers
$browsers static
Initial value:
= array(
        array(
            'browser' => 'Google Chrome on Linux',
            'browserName' => 'chrome',
            'sessionStrategy' => 'shared',
            'desiredCapabilities' => array()
        ),
    )
Definition at line 63 of file MyModuleFunctionalTest.php.
The documentation for this class was generated from the following file:
htdocs/modulebuilder/template/test/phpunit/MyModuleFunctionalTest.php