Dolibarr: Facturation Class Reference
Facturation Class Reference
Class to manage invoices for pos module (cashdesk)
Public Member Functions
__construct ()
Constructor.
ajoutArticle ()
Add a product into cart.
supprArticle ($aArticle)
Remove a product from panel.
calculTotaux ()
Calculation of total HT, total TTC and VAT amounts.
raz ()
Reset attributes.
id ($aId=null)
Getter for id.
ref ($aRef=null)
Getter for ref.
qte ($aQte=null)
Getter for qte.
stock ($aStock=null)
Getter for stock.
remisePercent ($aRemisePercent=null)
Getter for remise_percent.
montantRemise ($aMontantRemise=null)
Getter for montant_remise.
prix ($aPrix=null)
Getter for prix.
tva ($aTva=null)
Getter for tva.
numInvoice ($aNumFacture=null)
Get num invoice.
getSetPaymentMode ($aModeReglement=null)
Get payment mode.
montantEncaisse ($aMontantEncaisse=null)
Get amount.
montantRendu ($aMontantRendu=null)
Get amount.
paiementLe ($aPaiementLe=null)
Get payment date.
prixTotalHt ($aTotalHt=null)
Get total HT.
montantTva ($aMontantTva=null)
Get amount vat.
prixTotalTtc ($aTotalTtc=null)
Get total TTC.
Public Attributes
$id
Protected Attributes
$ref
$qte
$stock
$remise_percent
$montant_remise
$prix
$tva
$num_facture
Attributs persistants : utilises pour toute la duree de la vente (jusqu'a validation ou annulation) string $num_facture => Numero de la facture (de la forme FAYYMM-XXXX) string $mode_reglement => Mode de reglement (ESP, CB ou CHQ) int $montant_encaisse => Montant encaisse en cas de reglement en especes int $montant_rendu => Monnaie rendue en cas de reglement en especes int $paiement_le => Date de paiement en cas de paiement differe.
$mode_reglement
$montant_encaisse
$montant_rendu
$paiement_le
$prix_total_ht
$montant_tva
$prix_total_ttc
Private Member Functions
razPers ()
Resetting persistent attributes.
Detailed Description
Class to manage invoices for pos module (cashdesk)
Definition at line 26 of file Facturation.class.php.
Member Function Documentation
ajoutArticle()
ajoutArticle ()
Add a product into cart.
Returns
void
Definition at line 95 of file Facturation.class.php.
calculTotaux()
calculTotaux ()
Calculation of total HT, total TTC and VAT amounts.
Returns
int Total
Definition at line 213 of file Facturation.class.php.
getSetPaymentMode()
getSetPaymentMode ($aModeReglement = null)
Get payment mode.
Parameters
int $aModeReglement Payment mode
Returns
int Payment mode
Definition at line 475 of file Facturation.class.php.
Referenced by razPers().
id()
id ($aId = null)
Getter for id.
Parameters
int $aId Id
Returns
int Id
Definition at line 291 of file Facturation.class.php.
Referenced by raz().
montantEncaisse()
montantEncaisse ($aMontantEncaisse = null)
Get amount.
Parameters
int $aMontantEncaisse Amount
Returns
int Amount
Definition at line 493 of file Facturation.class.php.
Referenced by razPers().
montantRemise()
montantRemise ($aMontantRemise = null)
Getter for montant_remise.
Parameters
int $aMontantRemise Amount
Returns
string Amount
Definition at line 405 of file Facturation.class.php.
Referenced by raz().
montantRendu()
montantRendu ($aMontantRendu = null)
Get amount.
Parameters
int $aMontantRendu Amount
Returns
int Amount
Definition at line 511 of file Facturation.class.php.
Referenced by razPers().
montantTva()
montantTva ($aMontantTva = null)
Get amount vat.
Parameters
int $aMontantTva Amount vat
Returns
int Amount vat
Definition at line 563 of file Facturation.class.php.
Referenced by razPers().
numInvoice()
numInvoice ($aNumFacture = null)
Get num invoice.
Parameters
string $aNumFacture Invoice ref
Returns
string Invoice ref
Definition at line 458 of file Facturation.class.php.
References $num_facture.
Referenced by razPers().
paiementLe()
paiementLe ($aPaiementLe = null)
Get payment date.
Parameters
integer $aPaiementLe Date
Returns
integer Date
Definition at line 529 of file Facturation.class.php.
Referenced by razPers().
prix()
prix ($aPrix = null)
Getter for prix.
Parameters
int $aPrix Price
Returns
string Stock
Definition at line 423 of file Facturation.class.php.
Referenced by raz().
prixTotalHt()
prixTotalHt ($aTotalHt = null)
Get total HT.
Parameters
int $aTotalHt Total amount
Returns
int Total amount
Definition at line 546 of file Facturation.class.php.
Referenced by razPers().
prixTotalTtc()
prixTotalTtc ($aTotalTtc = null)
Get total TTC.
Parameters
int $aTotalTtc Amount ttc
Returns
int Amount ttc
Definition at line 580 of file Facturation.class.php.
Referenced by razPers().
qte()
qte ($aQte = null)
Getter for qte.
Parameters
int $aQte Qty
Returns
int Qty
Definition at line 337 of file Facturation.class.php.
Referenced by raz().
raz()
raz ()
Reset attributes.
Returns
void
Definition at line 252 of file Facturation.class.php.
References id(), montantRemise(), prix(), qte(), ref(), remisePercent(), stock(), and tva().
Referenced by __construct().
razPers()
razPers () private
Resetting persistent attributes.
Returns
void
Definition at line 269 of file Facturation.class.php.
References getSetPaymentMode(), montantEncaisse(), montantRendu(), montantTva(), numInvoice(), paiementLe(), prixTotalHt(), and prixTotalTtc().
Referenced by __construct().
ref()
ref ($aRef = null)
Getter for ref.
Parameters
string $aRef Ref
Returns
string Ref
Definition at line 314 of file Facturation.class.php.
Referenced by raz().
remisePercent()
remisePercent ($aRemisePercent = null)
Getter for remise_percent.
Parameters
string $aRemisePercent Discount
Returns
string Discount
Definition at line 382 of file Facturation.class.php.
Referenced by raz().
stock()
stock ($aStock = null)
Getter for stock.
Parameters
string $aStock Stock
Returns
string Stock
Definition at line 359 of file Facturation.class.php.
Referenced by raz().
supprArticle()
supprArticle ($aArticle)
Remove a product from panel.
Parameters
int $aArticle Id of line into cart to remove
Returns
void
Definition at line 188 of file Facturation.class.php.
tva()
tva ($aTva = null)
Getter for tva.
Parameters
int $aTva Vat
Returns
int Vat
Definition at line 441 of file Facturation.class.php.
Referenced by raz().
Member Data Documentation
$num_facture
$num_facture protected
Attributs persistants : utilises pour toute la duree de la vente (jusqu'a validation ou annulation) string $num_facture => Numero de la facture (de la forme FAYYMM-XXXX) string $mode_reglement => Mode de reglement (ESP, CB ou CHQ) int $montant_encaisse => Montant encaisse en cas de reglement en especes int $montant_rendu => Monnaie rendue en cas de reglement en especes int $paiement_le => Date de paiement en cas de paiement differe.
int $prix_total_ht => Prix total hors taxes int $montant_tva => Montant total de la TVA, tous taux confondus int $prix_total_ttc => Prix total TTC
Definition at line 66 of file Facturation.class.php.
Referenced by numInvoice().
The documentation for this class was generated from the following file:
htdocs/cashdesk/class/Facturation.class.php