Dolibarr: EvalMath Class Reference
EvalMath Class Reference
Class EvalMath.
Public Member Functions
__construct ()
Constructor.
e ($expr)
Evaluate.
evaluate ($expr)
Evaluate.
vars ()
vars
trigger ($code, $msg, $info=null)
trigger an error, but nicely, if need be
Public Attributes
$suppress_errors = false
$last_error = null
$last_error_code = null
$v = array('e' => 2.71, 'pi' => 3.14159)
$f = array()
$vb = array('e', 'pi')
$fb
Private Member Functions
funcs ()
vars
nfx ($expr)
Convert infix to postfix notation.
pfx ($tokens, $vars=array())
evaluate postfix notation
Detailed Description
Class EvalMath.
Definition at line 97 of file evalmath.class.php.
Member Function Documentation
e()
e ($expr)
Evaluate.
Parameters
string $expr String
Returns
boolean|number|NULL|mixed Result
Definition at line 134 of file evalmath.class.php.
References evaluate().
evaluate()
evaluate ($expr)
Evaluate.
Parameters
string $expr String
Returns
boolean|number|NULL|mixed Result
Definition at line 145 of file evalmath.class.php.
References trigger().
Referenced by e().
funcs()
funcs () private
vars
Returns
string Output
Definition at line 213 of file evalmath.class.php.
nfx()
nfx ($expr) private
Convert infix to postfix notation.
Parameters
string $expr Expression
Returns
string Output
Definition at line 230 of file evalmath.class.php.
pfx()
pfx ($tokens, $vars = array()) private
evaluate postfix notation
Parameters
string $tokens Expression
array $vars Array
Returns
string Output
Definition at line 375 of file evalmath.class.php.
trigger()
trigger ($code, $msg, $info = null)
trigger an error, but nicely, if need be
Parameters
string $code Code
string $msg Msg
string | null $info String
Returns
boolean False
Definition at line 466 of file evalmath.class.php.
Referenced by evaluate().
vars()
vars ()
vars
Returns
string Output
Definition at line 200 of file evalmath.class.php.
Member Data Documentation
$fb
$fb
Initial value:
= array(
    'sin', 'sinh', 'arcsin', 'asin', 'arcsinh', 'asinh', 'cos', 'cosh', 'arccos', 'acos', 'arccosh', 'acosh', 'tan', 'tanh', 'arctan', 'atan', 'arctanh', 'atanh', 'sqrt', 'abs', 'ln', 'log', 'intval')
Definition at line 115 of file evalmath.class.php.
The documentation for this class was generated from the following file:
htdocs/core/class/evalmath.class.php